import {SAMPLE_PATH} from './sample-path.js';
import test from 'node:test';import assert from 'node:assert/strict';import ExcelJS from 'exceljs';import JSZip from 'jszip';import fs from 'node:fs';import {columns,inspect,prepare} from '../src/engine.js';import {analyze,bucket,discover,safeSheetName} from '../src/analysis.js';import {generate} from '../src/export.js';
fs.mkdirSync('work',{recursive:true});
const samplePath=process.env.BF_SAMPLE_PATH||SAMPLE_PATH;
const model={header:0,rows:[['Date','Amount','Category','Currency'],['2026-01-01',100,' A ','EUR'],['2026-01-02',-30,'A','EUR'],['2026-02-01',0,'','EUR'],['invalid','bad','a','EUR'],['2026-02-03',5,'A','USD']]};model.columns=columns(model.rows,0);const c={selected:[0,1,2,3],roles:{Date:0,Amount:1,Category:2,Currency:3},period:'all',reports:['Report Data','Inflows','Outflows','Analysis'],groups:[{column:2,mode:'all',chart:true}],timeGrouping:'month'};
test('currency-safe KPIs, blank groups, zero/invalid amounts and rankings reconcile',()=>{const d=prepare(model,c),a=analyze(model,c,d),s=a.sections.find(x=>x.currency==='EUR');assert.equal(s.summary.count,4);assert.equal(s.summary.totalIn,100);assert.equal(s.summary.totalOut,-30);assert.equal(s.summary.net,70);assert.equal(s.summary.margin,.7);assert.equal(s.summary.averageOut,-30);assert.equal(s.invalidDates,1);assert.equal(a.groups[0].rows.reduce((n,r)=>n+r.count,0),5);assert.equal(a.groups[0].rows.filter(r=>r.label==='A').length,2);assert.ok(a.groups[0].rows.some(r=>r.label==='No value'));assert.equal(s.rankings.outflows[0].totalOut,-30);});
test('universal columns, selected values, date buckets and collision names',()=>{const d=prepare(model,c);for(const col of model.columns){const g={column:col.id,mode:'all'},values=discover(d.records,g,c);const a=analyze(model,{...c,groups:[{...g,mode:'one',values:[values[0].key]}]},d);assert.ok(a.groups[0].rows.length);assert.ok(a.groups[0].rows.every(r=>r.key===values[0].key));}assert.equal(bucket('2026-01-01','week'),'2025-12-29 (week)');assert.equal(bucket('2026-12-01','quarter'),'2026 Q4');const used=new Set();const first=safeSheetName('bad/:*?[]'.repeat(8),used),second=safeSheetName('bad/:*?[]'.repeat(8),used);assert.ok(first.length<=31&&second.length<=31&&first!==second);assert.throws(()=>analyze(model,{...c,groups:[{column:2,mode:'selected',values:[]}]},d),/at least one/);});
test('zero and negative-only ratios stay finite; missing roles remain honest',()=>{for(const amount of [0,-3]){const m={header:0,rows:[['Amount'],[amount]]};m.columns=columns(m.rows,0);const cfg={selected:[0],roles:{Amount:0},period:'all',reports:['Analysis']};const a=analyze(m,cfg,prepare(m,cfg));assert.equal(a.sections[0].summary.margin,null);assert.equal(a.dateAvailable,false);assert.ok(a.sections[0].summary.ratio==null||Number.isFinite(a.sections[0].summary.ratio));}const cfg={...c,roles:{Date:0},reports:['Analysis'],groups:[]};assert.equal(analyze(model,cfg,prepare(model,cfg)).amountAvailable,false);});
test('native charts and locked AutoFilter are present in actual OOXML',async()=>{const d=prepare(model,c),bytes=await generate(model,c,d),zip=await JSZip.loadAsync(bytes);fs.writeFileSync('work/analysis-edge.xlsx',bytes);const out=new ExcelJS.Workbook();await out.xlsx.load(bytes);for(const sheet of out.worksheets){assert.equal(Boolean(sheet.autoFilter),sheet.name==='Report Data');const xml=await zip.file(`xl/worksheets/sheet${sheet.id}.xml`).async('string');assert.equal(/<autoFilter\b/.test(xml),sheet.name==='Report Data');assert.equal(/<tableParts\b/.test(xml),false);}const types=await zip.file('[Content_Types].xml').async('string');assert.match(types,/application\/vnd.openxmlformats-officedocument.drawing\+xml/);assert.doesNotMatch(types,/drawingml.drawing/);const names=Object.keys(zip.files).filter(n=>/^xl\/charts\/chart\d+\.xml$/.test(n));assert.ok(names.length>=4);const xml=(await Promise.all(names.map(n=>zip.file(n).async('string')))).join('');assert.match(xml,/<c:barChart>/);assert.match(xml,/<c:lineChart>/);assert.match(xml,/<c:doughnutChart>/);assert.match(xml,/Analysis.*!\$/);});
test('sample comprehensive workbook groups and time summaries reconcile',{skip:!fs.existsSync(samplePath)},async()=>{const source=new ExcelJS.Workbook();await source.xlsx.readFile(samplePath);const m=inspect(source.worksheets[0]);m.columns=columns(m.rows,m.header);const cfg={...c,selected:[2,3,4,5,9],roles:{Date:2,Description:3,Details:4,Amount:5},groups:[{column:3,mode:'all',chart:true},{column:2,mode:'all',dateLevel:'month',chart:true},{column:5,mode:'all'}]};const d=prepare(m,cfg),bytes=await generate(m,cfg,d),a=d.analysis;fs.writeFileSync('work/analysis-sample-test.xlsx',bytes);assert.equal(a.sections[0].summary.count,94);assert.ok(Math.abs(a.sections[0].summary.net-2276.27)<1e-7);for(const g of a.groups){assert.equal(g.rows.reduce((n,r)=>n+r.count,0),94);assert.ok(Math.abs(g.rows.reduce((n,r)=>n+r.net,0)-d.net)<1e-7);}assert.equal(a.sections[0].time.reduce((n,r)=>n+r.count,0),94);});

test('large group cardinality and every time level stay period-consistent',()=>{const m={header:0,rows:[['Date','Amount','Custom'],...Array.from({length:5000},(_,i)=>['2026-01-01',i%2?-.01:.03,'Value '+i])]};m.columns=columns(m.rows,0);for(const level of ['day','week','month','quarter','year']){const cfg={...c,roles:{Date:0,Amount:1},groups:[{column:2,mode:'all'}],timeGrouping:level,period:'custom',start:'2026-01-01',end:'2026-01-01'};const d=prepare(m,cfg),a=analyze(m,cfg,d);assert.equal(a.groups[0].rows.length,5000);assert.equal(a.sections[0].time.length,1);assert.ok(Math.abs(a.sections[0].summary.net-50)<1e-9);}});


test('Notes 1 and 2: left alignment, dedicated charts and reciprocal internal links',async()=>{const d=prepare(model,c),bytes=await generate(model,c,d),out=new ExcelJS.Workbook();await out.xlsx.load(bytes);const summary=out.getWorksheet('Analysis - Summary'),graphs=out.getWorksheet('Analysis - Charts');assert.ok(summary&&graphs);assert.equal(summary.getCell('A2').value.hyperlink,"#'Analysis - Charts'!A1");assert.equal(graphs.getCell('A2').value.hyperlink,"#'Analysis - Summary'!A1");assert.equal(graphs.views[0].ySplit,3);for(const sheet of out.worksheets)sheet.eachRow(row=>row.eachCell(cell=>{if(cell.type!==ExcelJS.ValueType.Merge&&cell.value!=null){assert.equal(cell.alignment.horizontal,'left');assert.equal(cell.alignment.vertical,'middle');}}));const zip=await JSZip.loadAsync(bytes);for(const sheet of out.worksheets){const xml=await zip.file(`xl/worksheets/sheet${sheet.id}.xml`).async('string');assert.equal(/<drawing\b/.test(xml),sheet.name==='Analysis - Charts');}assert.equal(d.analysis.groups.length,1);const drawing=await zip.file('xl/drawings/drawing1.xml').async('string');assert.match(drawing,/<xdr:row>7<\/xdr:row>/);assert.ok(graphs.getCell('A6').value.hyperlink.includes('Analysis - Summary'));});
