import {SAMPLE_PATH} from './sample-path.js';
import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';
const browser=await chromium.launch({executablePath:process.env.BF_BROWSER_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,downloadsPath:'D:/DETLENG2/businessflow-detleng/work/downloads'});const page=await browser.newPage({acceptDownloads:true,viewport:{width:1440,height:1000}});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));await page.goto('http://127.0.0.1:5173');
for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:1000});await page.screenshot({path:`work/home-${width}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`horizontal overflow ${width}`);if(width<1100){await page.locator('#menu').click();assert.equal(await page.locator('#menu').getAttribute('aria-expanded'),'true');await page.locator('#navigation a[href="#privacy"]').click();assert.equal(await page.locator('#menu').getAttribute('aria-expanded'),'false');}}
await page.setViewportSize({width:1440,height:1000});await page.locator('.hero .start').click();await page.locator('#file').setInputFiles(SAMPLE_PATH);await page.locator('#header').waitFor();assert.equal(await page.locator('#header').inputValue(),'5');await page.locator('#next').click();await page.locator('#clear').click();await page.locator('#next').click();assert.match(await page.locator('#error').innerText(),/Select at least/);await page.locator('#all').click();await page.locator('#next').click();await page.locator('#role-2').selectOption('Date');await page.locator('#role-5').selectOption('Amount');await page.locator('#role-6').selectOption('Currency');await page.locator('#sort').selectOption('2');await page.locator('#next').click();await page.locator('#next').click();await page.locator('[data-period=custom]').click();await page.locator('#start').fill('2026-06-01');await page.locator('#end').fill('2026-06-30');await page.locator('#end').dispatchEvent('change');assert.match(await page.locator('#count').innerText(),/38 records/);
// Auth shell must preserve a partially configured report and never transmit form fields.
const before=requests.length;await page.locator('#login').click();await page.locator('#email').fill('test@example.com');await page.locator('#password').fill('SENSITIVE_TEST_ONLY');await page.locator('#auth-form button[type=submit]').click();await page.locator('#continue-free').click();assert.equal(await page.locator('[data-period=custom]').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.equal(requests.slice(before).length,0);assert.equal(await page.locator('#login').evaluate(e=>e===document.activeElement),true);
await page.locator('#login').click();await page.locator('#create-mode').click();await page.locator('#username').fill('Review User');await page.locator('#email').fill('review@example.com');await page.locator('#password').fill('temporary');await page.locator('#confirm-password').fill('temporary');await page.locator('#show-password').click();assert.equal(await page.locator('#password').getAttribute('type'),'text');await page.locator('#auth-form button[type=submit]').click();await page.locator('#continue-free').click();await page.locator('#login').click();assert.equal(await page.locator('#password').inputValue(),'');await page.keyboard.press('Escape');assert.equal(await page.locator('#auth').evaluate(e=>e.open),false);
await page.locator('[data-period=all]').click();await page.locator('#generate').click();await page.locator('#download').waitFor({timeout:30000});assert.match(await page.locator('#screen').innerText(),/12,643.28/);await page.locator('#preview-button').click();assert.equal(await page.locator('#preview-content tbody tr').count(),20);await page.locator('#preview-sheet').selectOption('Outflows');await page.screenshot({path:'work/results-desktop.png',fullPage:true});
const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;const failure=await download.failure();if(failure){console.log('Download automation limitation:',failure);const bytes=await page.locator('#download').evaluate(async a=>Array.from(new Uint8Array(await (await fetch(a.href)).arrayBuffer())));fs.writeFileSync('work/browser-generated.xlsx',Buffer.from(bytes));}else await download.saveAs('work/browser-generated.xlsx');assert.ok(fs.statSync('work/browser-generated.xlsx').size>1000);
for(const width of [1024,768,390]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`work/results-${width}.png`,fullPage:true});}
await page.locator('#menu').click();await page.locator('#login').click();assert.ok(await page.locator('#auth').isVisible());await page.locator('#create-mode').click();await page.screenshot({path:'work/auth-mobile.png'});await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('button')).transitionDuration),'0s');
assert.equal(await page.locator('a[href="https://lfds.detleng.com/"]').count(),2);assert.equal(await page.locator('a[href="https://network.detleng.com/"]').count(),2);assert.deepEqual(errors,[]);assert.equal(requests.filter(r=>r.method!=='GET').length,0);console.log('Browser checks passed: four responsive widths, upload, header, columns, roles, date range, preview, generated download bytes, desktop/mobile auth, privacy, focus, Escape, reduced motion, ecosystem links, no console errors.');await browser.close();
