import {test} from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import {definition,selected,validateDefinition,addColumn,CAPACITIES,sampleRange,fileName} from '../src/builder-schema.js';
import {sampleRecords,money} from '../src/builder-data.js';
import {buildWorkbook,sourceModel} from '../src/builder-output.js';
import {recognizeBuilder} from '../src/builder-import.js';
import {prepare,inspect,columns} from '../src/engine.js';
import {generate} from '../src/export.js';
import {detectReport,importDataset} from '../src/report-import.js';
import {sessionDataset,computeLive,initialFilters} from '../src/live-engine.js';
const config=m=>({roles:m.builder.roles,selected:m.columns.map(c=>c.id),numberStyle:m.builder.numberStyle,dateOrder:m.builder.dateOrder,period:'all',reports:['Report Data','Inflows','Outflows','Analysis'],groups:[],timeGrouping:'auto'});
const read=async buffer=>{const w=new ExcelJS.Workbook();await w.xlsx.load(buffer);return w;};
for(const id of ['sales','products','customers','suppliers','transactions','complete'])test(`${id}: twin schema outputs, real cell types, bounded styling, validation and metadata`,async()=>{
 const d=definition(id);d.rowCapacity=100;d.columns.forEach(c=>c.selected=true);
 const [blank,sample]=await Promise.all(['blank','sample'].map(mode=>buildWorkbook(d,mode,{seed:42,now:new Date('2026-10-08')})));
 for(const [out,mode]of [[blank,'blank'],[sample,'sample']]){const w=await read(out.buffer),sheet=w.getWorksheet(d.sheetName);assert.equal(sheet.rowCount,101);assert.equal(sheet.columnCount,selected(d).length);assert.equal(w.getWorksheet('_BF_Metadata').state,'hidden');assert.equal(w.getWorksheet('_BF_Lists').state,'veryHidden');assert.equal(out.metadata.mode,mode);assert.equal(out.metadata.sampleData,mode==='sample');assert.deepEqual(sheet.getRow(1).values.slice(1),selected(d).map(c=>c.label));assert.equal(sheet.views[0].ySplit,1);assert(sheet.autoFilter);assert.equal(sheet.getCell(2,sheet.columnCount+1).fill?.type,undefined);assert.equal(sheet.getCell(102,1).fill?.type,undefined);for(let i=0;i<selected(d).length;i++){const c=selected(d)[i];if(mode==='blank')assert.equal(sheet.getCell(2,i+1).value,null);else if(c.type==='Date')assert(sheet.getCell(2,i+1).value instanceof Date);else if(['Number','Amount','Quantity','Percentage'].includes(c.type))assert.equal(typeof sheet.getCell(2,i+1).value,'number');if(c.validation.length)assert.equal(sheet.getCell(2,i+1).dataValidation.type,'list');}assert.equal(out.metadata.columns[0].position,1);}
 const rec=recognizeBuilder(await read(sample.buffer));assert(rec.model.builder.recognized);assert.equal(prepare(rec.model,config(rec.model)).records.length,100);
});
test('sample relationships, date boundaries, finite totals and event signs are coherent',()=>{
 for(const id of ['sales','products','customers','suppliers','transactions','complete']){const d=definition(id);d.columns.forEach(c=>c.selected=true);d.rowCapacity=5000;d.sampleMonths='custom';d.sampleStart='2024-02-01';d.sampleEnd='2024-02-29';const cols=selected(d),rows=sampleRecords(d,7),at=(row,key)=>row[cols.findIndex(c=>c.id===key)];assert.deepEqual(rows,sampleRecords(d,7));const skus=new Map(),customers=new Map(),suppliers=new Map();let pos=0,neg=0;for(const row of rows){assert(at(row,'date')>=new Date('2024-02-01')&&at(row,'date')<=new Date('2024-02-29'));const amount=at(row,'amount');assert(Number.isFinite(amount));if(amount>0)pos++;if(amount<0)neg++;for(const [key,name,map]of [['sku','product',skus],['customerId','customer',customers],['supplierId','supplier',suppliers]]){if(cols.some(c=>c.id===key)){if(map.has(at(row,key)))assert.equal(map.get(at(row,key)),at(row,name));map.set(at(row,key),at(row,name));}}if(id==='sales'){assert.equal(Math.abs(amount),money(at(row,'quantity')*at(row,'price')*(1-at(row,'discount'))*(1+at(row,'tax'))));assert.equal(Math.sign(amount),at(row,'paymentStatus')==='Refunded'?-1:1);}if(id==='products'){const ev=at(row,'movement');assert.equal(Math.sign(amount),['Purchase','Customer Refund'].includes(ev)?-1:['Transfer','Adjustment'].includes(ev)?0:1);assert.equal(Math.abs(amount),money(at(row,'quantity')*at(row,'price')));}if(id==='suppliers')assert.equal(Math.sign(amount),at(row,'purchase')==='Supplier Credit'?1:-1);if(id==='complete')assert.equal(Math.abs(amount),money(at(row,'quantity')*at(row,'price')));for(let i=0;i<cols.length;i++)if(cols[i].required)assert.notEqual(row[i],null);}
 assert(pos>0&&neg>0);}
});
test('capacities, custom settings, renamed order and uniqueness are enforced',async()=>{
 for(const n of [...CAPACITIES,137]){const d=definition();d.rowCapacity=n;assert.equal(sampleRecords(d,1).length,n);const w=await read((await buildWorkbook(d,'blank')).buffer);assert.equal(w.getWorksheet('Transactions').rowCount,n+1);}
 const d=definition('custom');addColumn(d);assert.equal(selected(d).length,1);validateDefinition(d);for(const count of [99,5001,100.5,NaN]){d.rowCapacity=count;assert.throws(()=>validateDefinition(d),/row count/);}d.rowCapacity=100;addColumn(d);d.columns[1].label=d.columns[0].label;assert.throws(()=>validateDefinition(d),/unique heading/);d.columns[1].label='Amount';d.columns[1].type='Amount';d.columns[1].role='Amount';d.columns.reverse();const out=await buildWorkbook(d,'sample',{seed:5});assert.equal(out.metadata.columns[0].label,'Amount');assert.equal(typeof out.model.rows[1][0],'number');d.columns[1].role='Amount';assert.throws(()=>validateDefinition(d),/one column/);d.columns[1].role='';d.workbookName='=Safe<>/:File';assert(!/[<>:"/\\|?*]/.test(fileName(d,'blank')));d.columns[1].label='=HYPERLINK("evil")';const sheet=(await read((await buildWorkbook(d,'blank')).buffer)).worksheets[0];assert.equal(typeof sheet.getCell(1,2).value,'string');assert.throws(()=>sampleRange({...d,sampleMonths:'custom',sampleStart:'2024-02-30',sampleEnd:'2024-03-03'}),/valid sample/);
});
test('filled blank return, reorder/rename reconciliation and blank-row exclusion',async()=>{
 const d=definition('transactions');d.rowCapacity=100;const w=await read((await buildWorkbook(d,'blank')).buffer),s=w.getWorksheet('Transactions'),cols=selected(d);s.getCell(2,cols.findIndex(c=>c.id==='date')+1).value=new Date('2026-02-03');s.getCell(2,cols.findIndex(c=>c.id==='amount')+1).value=125.55;s.getCell(3,cols.findIndex(c=>c.id==='amount')+1).value=-40.2;
 let r=recognizeBuilder(w);assert.equal(prepare(r.model,config(r.model)).records.length,2);assert.equal(prepare(r.model,config(r.model)).net,85.35);const a=s.getColumn(1).values,b=s.getColumn(2).values;s.getColumn(1).values=b;s.getColumn(2).values=a;r=recognizeBuilder(w);assert.equal(r.model.builder.roles.Date,1);assert.equal(r.model.columns.find(c=>c.id===1).schemaId,'date');s.getCell(1,cols.findIndex(c=>c.id==='amount')+1).value='Renamed amount';r=recognizeBuilder(w);assert.equal(r.model.builder.roles.Amount,undefined);assert.match(r.model.builder.warning,/Amount/);w.getWorksheet('_BF_Metadata').getCell('B1').value='{broken';assert.match(recognizeBuilder(w).warning,/damaged/);
});
test('Complete sample → shared report → metadata reopen → shared analytics numerical parity',async()=>{
 const d=definition('complete');d.rowCapacity=5000;const begin=performance.now(),out=await buildWorkbook(d,'sample',{seed:88}),elapsed=performance.now()-begin,m=out.model,c=config(m);const category=m.columns.find(x=>x.schemaId==='category');c.groups=[{column:category.id,mode:'all',values:[],sort:'label',direction:'asc',dateLevel:'day',chart:true}];const data=prepare(m,c),report=await generate(m,c,data),w=await read(report),reopened=importDataset(detectReport(w),null,'Saved report'),current=sessionDataset(m,c,data,'Sample');const a=computeLive(current,initialFilters(current)),b=computeLive(reopened,initialFilters(reopened));assert.deepEqual(a.summary,b.summary);assert.equal(data.records.length,5000);const amountIndex=selected(d).findIndex(c=>c.role==='Amount');const independent=out.model.rows.slice(1).reduce((s,r)=>s+Math.round(r[amountIndex]*100),0)/100;assert(Math.abs(data.net-independent)<1e-8);assert.equal(w.getWorksheet('Report Data').rowCount,5001);for(const s of w.worksheets)if(s.name!=='Report Data')assert.equal(s.autoFilter,undefined);console.log(JSON.stringify({builderRecords:5000,generationMs:Math.round(elapsed),totalIn:data.totalIn,totalOut:data.totalOut,net:data.net,analyticsParity:true}));
});
