import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';import ExcelJS from 'exceljs';
const base=process.env.BF_BASE_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:'))external.push(r.url());if(r.method()!=='GET')external.push(r.method()+':'+r.url());});
const ready=()=>page.waitForFunction(()=>document.getElementById('live-status')?.textContent.includes('Updated locally.'));
const bytes=async id=>Buffer.from(await page.locator(id).evaluate(async a=>Array.from(new Uint8Array(await(await fetch(a.href)).arrayBuffer()))));
const next=()=>page.locator('#builder-next').click();
await page.goto(base);assert.equal(await page.locator('.entry-paths article').count(),3);await page.locator('.build-workbook').click();await page.locator('[name=builder-template][value=complete]').check();await next();await page.locator('#builder-all').click();await next();await page.locator('[data-field=customer]').count();await page.locator('[data-field=counterparty] [data-property=label]').fill('Trading Partner');await page.locator('[data-field=counterparty] [data-property=label]').blur();await page.locator('[data-field=counterparty] [data-move=up]').click();await next();await page.locator('#builder-capacity-choice').selectOption('5000');await page.locator('#builder-date').selectOption('yyyy-mm-dd');await next();assert.match(await page.locator('#builder').innerText(),/Trading Partner/);await next();await page.locator('#builder-period').selectOption('custom');await page.locator('#builder-start').fill('2026-01-01');await page.locator('#builder-end').fill('2026-06-30');await page.locator('#builder-end').blur();
await page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});const axe=await page.evaluate(async()=>await axe.run(document.getElementById('builder')));assert.deepEqual(axe.violations.filter(v=>['serious','critical'].includes(v.impact)).map(v=>v.id),[]);
await page.setViewportSize({width:390,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'work/builder-output-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
await page.evaluate(()=>{window.builderHeartbeats=0;window.builderTimer=setInterval(()=>window.builderHeartbeats++,25);});const started=Date.now();await page.locator('#builder-sample').click();await page.locator('#builder-download').waitFor({timeout:120000});const elapsed=Date.now()-started;assert(await page.evaluate(()=>window.builderHeartbeats)>5);await page.evaluate(()=>clearInterval(window.builderTimer));assert.equal(await page.locator('#builder tbody tr').count(),10);const sample=await bytes('#builder-download');fs.writeFileSync('work/builder-complete-sample.xlsx',sample);await page.screenshot({path:'work/builder-sample-desktop.png',fullPage:false});
const w=new ExcelJS.Workbook();await w.xlsx.load(sample);const source=w.getWorksheet('Business Data'),meta=JSON.parse(w.getWorksheet('_BF_Metadata').getCell('B1').value),ai=meta.columns.find(c=>c.role==='Amount').position;let sum=0,inflow=0,outflow=0;for(let r=2;r<=5001;r++){const x=Math.round(source.getCell(r,ai).value*100);sum+=x;if(x>0)inflow+=x;if(x<0)outflow+=x;}
await page.locator('#builder-use').click();await page.locator('#next').click();assert.equal(await page.locator(`#role-${ai-1}`).inputValue(),'Amount');await page.locator('#next').click();await page.locator('#add-group').click();const gi=meta.columns.find(c=>c.id==='category').position-1;await page.locator('[data-group="0"] [data-key=column]').selectOption(String(gi));await page.locator('[data-group="0"] [data-key=chart]').check();await page.locator('#next').click();assert.match(await page.locator('#count').innerText(),/5000 records/);await page.locator('#generate').click();await page.locator('#download').waitFor({timeout:120000});fs.writeFileSync('work/builder-processed-report.xlsx',await bytes('#download'));await page.locator('#open-live').click();await ready();assert.equal(await page.locator('[data-metric=count]').innerText(),'5,000');const net=(sum/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});assert.equal(await page.locator('[data-metric=net]').innerText(),net);const before=await page.locator('.live-kpis').count();await page.screenshot({path:'work/builder-analytics.png',fullPage:false});
await page.reload();await page.locator('.entry-paths .explore-existing').click();await page.locator('#existing-file').setInputFiles('work/builder-processed-report.xlsx');await ready();assert.equal(await page.locator('[data-metric=count]').innerText(),'5,000');assert.equal(await page.locator('[data-metric=net]').innerText(),net);
await page.reload();await page.locator('.hero .start').click();await page.locator('#file').setInputFiles('work/builder-complete-sample.xlsx');await page.locator('#header').waitFor();assert.match(await page.locator('#screen').innerText(),/workbook recognized/);await page.locator('#next').click();await page.locator('#next').click();assert.equal(await page.locator(`#role-${ai-1}`).inputValue(),'Amount');
// Blank owner return: download an empty workbook, fill two rows, source upload restores roles.
await page.reload();await page.locator('.build-workbook').click();await next();await next();await next();await page.locator('#builder-capacity-choice').selectOption('100');await next();await next();await page.locator('#builder-blank').click();await page.locator('#builder-download').waitFor();assert.equal(await page.locator('#builder-use').count(),0);const bw=new ExcelJS.Workbook();await bw.xlsx.load(await bytes('#builder-download'));const bmeta=JSON.parse(bw.getWorksheet('_BF_Metadata').getCell('B1').value),bs=bw.getWorksheet('Transactions'),amount=bmeta.columns.find(c=>c.role==='Amount').position,di=bmeta.columns.find(c=>c.role==='Date').position;bs.getCell(2,di).value=new Date('2026-02-01');bs.getCell(2,amount).value=125.55;bs.getCell(3,di).value=new Date('2026-02-02');bs.getCell(3,amount).value=-40.2;fs.writeFileSync('work/builder-filled-blank.xlsx',Buffer.from(await bw.xlsx.writeBuffer()));
await page.reload();await page.locator('.hero .start').click();await page.locator('#file').setInputFiles('work/builder-filled-blank.xlsx');await page.locator('#header').waitFor();assert.match(await page.locator('#screen').innerText(),/workbook recognized/);await page.locator('#next').click();await page.locator('#next').click();assert.equal(await page.locator(`#role-${amount-1}`).inputValue(),'Amount');await page.locator('#next').click();await page.locator('#next').click();assert.match(await page.locator('#count').innerText(),/2 records/);await page.locator('#generate').click();await page.locator('#download').waitFor();await page.locator('#open-live').click();await ready();assert.equal(await page.locator('[data-metric=net]').innerText(),'85.35');
// Custom editor preserves state, blocks duplicate labels and supports a general non-monetary workbook.
await page.reload();await page.locator('.build-workbook').click();await page.locator('[name=builder-template][value=custom]').check();await next();await page.locator('#builder-add').click();await page.locator('#builder-add').click();await next();const labels=page.locator('[data-property=label]');await labels.nth(0).fill('Safe field');await labels.nth(1).fill('Safe field');await labels.nth(1).blur();await next();assert.match(await page.locator('#builder-error').innerText(),/unique heading/);await labels.nth(1).fill('Other field');await labels.nth(1).blur();await page.locator('[data-field=custom_2] [data-move=up]').click();await next();await page.locator('#builder-capacity').fill('99');await page.locator('#builder-capacity').blur();await next();assert.match(await page.locator('#builder-error').innerText(),/100 to 5,000/);await page.locator('#builder-capacity').fill('137');await page.locator('#builder-capacity').blur();await next();assert.match(await page.locator('#builder').innerText(),/will require an Amount/);await page.locator('#builder-back').click();await page.locator('#builder-back').click();assert.equal(await labels.nth(0).inputValue(),'Other field');await page.setViewportSize({width:390,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'work/builder-custom-mobile.png',fullPage:true});await page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});const fieldAxe=await page.evaluate(async()=>await axe.run(document.getElementById('builder')));assert.deepEqual(fieldAxe.violations.filter(v=>['serious','critical'].includes(v.impact)).map(v=>v.id),[]);
await page.locator('[data-field=custom_2] [data-remove]').click();assert.equal(await page.locator('[data-field]').count(),1);await page.locator('#builder-create').click();assert.equal(await page.locator('#file').count(),1);await page.reload();await page.locator('.build-workbook').click();await page.locator('#builder-home').click();assert.equal(await page.locator('.entry-paths article:visible').count(),3);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);const report={records:5000,generationMs:elapsed,inflows:inflow/100,outflows:outflow/100,net:sum/100,parity:true,externalRequests:external.length};fs.writeFileSync('work/builder-browser-results.json',JSON.stringify(report,null,2));console.log('Builder browser PASS',report);await browser.close();
