import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ExcelJS from 'exceljs';import {inspect,columns,number,date,period,prepare} from '../src/engine.js';import {generate} from '../src/export.js';
const config={selected:[0,1],roles:{Date:0,Amount:1},period:'all',reports:['Report Data','Inflows','Outflows'],numberStyle:'dot',dateOrder:'dmy'};
test('numbers preserve decimals, signs and zero; reject blanks and malformed text',()=>{assert.equal(number('(1,234.5678)'),-1234.5678);assert.equal(number('1.234,56','comma'),1234.56);assert.equal(number(''),null);assert.equal(number('12oops'),null);assert.equal(number('0'),0);assert.equal(number('1,23','dot'),null);});
test('dates honor explicit regional choice and reject rollover',()=>{assert.equal(date('03/04/2026','dmy'),'2026-04-03');assert.equal(date('03/04/2026','mdy'),'2026-03-04');assert.equal(date('31/02/2026'),null);assert.equal(date(1,'dmy',true),'1904-01-02');assert.equal(date('2026-10-07'),'2026-10-07');});
test('period boundaries include both endpoints and previous quarter crosses year',()=>{assert.deepEqual(period('previous-quarter','','',new Date(2026,0,10)),['2025-10-01','2025-12-31']);const model={rows:[['Date','Amount'],['01/01/2026',1],['31/01/2026',-2],['01/02/2026',0]],header:0};const d=prepare(model,{...config,period:'custom',start:'2026-01-01',end:'2026-01-31'});assert.equal(d.records.length,2);assert.equal(d.net,-1);});
test('blank and invalid amounts stay in report data; zeros never enter flows',()=>{const model={header:0,rows:[['Date','Amount'],['2026-01-01',10],['2026-01-02',-5],['2026-01-03',0],['2026-01-04','oops'],['2026-01-05',null]]};const copy=JSON.stringify(model);const d=prepare(model,config);assert.equal(d.records.length,5);assert.equal(d.inflows.length,1);assert.equal(d.outflows.length,1);assert.equal(d.invalid,1);assert.equal(d.blank,1);assert.equal(JSON.stringify(model),copy);assert.throws(()=>prepare(model,{...config,roles:{}}),/Amount/);assert.throws(()=>prepare(model,{...config,reports:[]}),/report/);});
test('duplicate headers remain distinct, sorting follows roles, date exclusions counted',()=>{const model={header:0,rows:[['Same','Same'],['02/01/2026',1],['01/01/2026',2],['invalid',3]]};assert.deepEqual(columns(model.rows,0).map(c=>c.id),[0,1]);const d=prepare(model,{...config,period:'custom',start:'2026-01-01',end:'2026-01-02',sort:0});assert.equal(d.records[0].amount,2);assert.equal(d.badDates,1);});
test('provided workbook detection, independent sums, export round trip and formulas',{skip:!fs.existsSync('D:/PROMPTS - Prompts/businessflow-detleng/04 source-for tes.xlsx')},async()=>{const path='D:/PROMPTS - Prompts/businessflow-detleng/04 source-for tes.xlsx';const before=fs.readFileSync(path);const w=new ExcelJS.Workbook();await w.xlsx.load(before);const model=inspect(w.worksheets[0]);model.columns=columns(model.rows,model.header);assert.equal(model.header,4);assert.equal(model.columns.length,9);const c={...config,selected:[2,3,4,5,9],roles:{Date:2,Description:3,Details:4,Amount:5,Notes:9},sort:2,direction:'asc'};const d=prepare(model,c);const independent=model.rows.slice(5).filter(r=>typeof r[5]==='number');assert.equal(d.records.length,independent.length);assert.equal(d.inflows.length,independent.filter(r=>r[5]>0).length);assert.equal(d.outflows.length,independent.filter(r=>r[5]<0).length);assert.ok(Math.abs(d.totalIn-independent.filter(r=>r[5]>0).reduce((s,r)=>s+r[5],0))<1e-8);const bytes=await generate(model,c,d);fs.writeFileSync('work/sample-generated.xlsx',Buffer.from(bytes));const out=new ExcelJS.Workbook();await out.xlsx.load(bytes);assert.deepEqual(out.worksheets.filter(s=>s.state==='visible').map(s=>s.name),c.reports);assert.equal(out.getWorksheet('_BF_Metadata').state,'hidden');assert.equal(out.getWorksheet('Report Data').rowCount,d.records.length+1);const flow=out.getWorksheet('Inflows');assert.equal(flow.getCell(d.inflows.length+3,4).value.formula,`SUM(D2:D${d.inflows.length+1})`);assert.equal(flow.getCell(d.inflows.length+3,4).value.result,d.totalIn);assert.equal(flow.views[0].ySplit,1);assert.equal(flow.autoFilter,undefined);assert.deepEqual(fs.readFileSync(path),before);console.log(JSON.stringify({records:d.records.length,inflows:d.inflows.length,outflows:d.outflows.length,totalIn:d.totalIn,totalOut:d.totalOut,net:d.net}));});

test('Excel early serial dates and modern dates normalize correctly',()=>{assert.equal(date(1),'1900-01-01');assert.equal(date(59),'1900-02-28');assert.equal(date(61),'1900-03-01');});
test('mixed currencies detected, export strings cannot become formulas',async()=>{const model={header:0,rows:[['Memo','Amount','Currency'],['=HYPERLINK("https://example.com")',1,'EUR'],['<script>',-2,'USD']]};model.columns=columns(model.rows,0);const c={...config,selected:[0,1,2],roles:{Amount:1,Currency:2},reports:['Report Data','Inflows','Outflows','Analysis']};const d=prepare(model,c);assert.equal(d.mixed,true);const bytes=await generate(model,c,d);const out=new ExcelJS.Workbook();await out.xlsx.load(bytes);assert.equal(out.getWorksheet('Report Data').getCell('A2').value,model.rows[1][0]);assert.ok(out.getWorksheet('Analysis - Summary').rowCount>20);assert.equal(d.analysis.sections.length,2);});

test('fills are bounded to report cells; Amount highlight stops at last data row',async()=>{const model={header:0,rows:[['Date','Amount'],['2026-01-01',3],['2026-01-02',-1]]};model.columns=columns(model.rows,0);const d=prepare(model,config);const bytes=await generate(model,config,d);const out=new ExcelJS.Workbook();await out.xlsx.load(bytes);for(const sheet of out.worksheets.filter(s=>s.state==='visible')){assert.equal(sheet.getCell(1,3).fill?.fgColor,undefined);assert.equal(sheet.getCell(2,3).fill?.fgColor,undefined);assert.equal(sheet.getCell(2,2).fill.fgColor.argb,'FFE5F1FC');const dataEnd=sheet.name==='Report Data'?3:2;assert.equal(sheet.getCell(dataEnd+1,2).fill?.fgColor,undefined);assert.equal(sheet.getRow(1).fill?.fgColor,undefined);assert.equal(sheet.getRow(2).fill?.fgColor,undefined);assert.equal(sheet.getColumn(2).fill?.fgColor,undefined);}});
