import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ExcelJS from 'exceljs';import {inspect,columns,prepare} from '../src/engine.js';import {suggestRoles,normalizeHeader} from '../src/role-suggestions.js';
const run=(headers,rows,metadata={})=>{const model={rows:[headers,...rows],header:0};model.columns=columns(model.rows,0);return suggestRoles(model,{selected:model.columns.map(c=>c.id),dateOrder:'dmy',numberStyle:'dot'},metadata);};
test('normalized multilingual aliases and safe extra fields',()=>{assert.equal(normalizeHeader('F. Válor'),'fvalor');const r=run(['FECHA','Descripción','IMPORTE','Quantity','Unit Price','Currency'],[['2025-01-01','Rent',-20,2,10,'EUR']]);assert.deepEqual(r.roles,{Date:0,Description:1,Amount:2,Currency:5});});
test('ambiguous amount and dates require review; metadata wins',()=>{const headers=['Date','Settlement Date','Amount','Net Amount'];const rows=[['2025-01-01','2025-01-02',10,9]];assert.deepEqual(run(headers,rows).roles,{});assert.equal(run(headers,rows).notices.length,2);const r=run(headers,rows,{Date:1,Amount:3});assert.deepEqual(r.roles,{Date:1,Amount:3});assert.equal(r.badges[3].kind,'recognized');});
test('contradictory values and arbitrary numbers never guessed',()=>{assert.deepEqual(run(['Date','Amount','Quantity','Unit Price'],[['not a date','bad',20,10]]).roles,{});assert.equal(run(['Amount','Debit','Credit'],[[20,5,10]]).roles.Amount,undefined);});
test('native dates and currencies provide strong patterns, IDs do not',()=>{const r=run(['Unknown','Money','ID'],Array.from({length:3},(_,i)=>[new Date(2025,0,i+1),'EUR',i+100]));assert.deepEqual(r.roles,{Date:0,Currency:1});});
test('sampling is bounded even for large sources',()=>{const start=performance.now();const r=run(['Amount'],Array.from({length:200000},()=>[5]));assert.equal(r.roles.Amount,0);assert.ok(performance.now()-start<2000);});
const fixture='C:/Users/mnvid/Downloads/Test Business Flow.xlsx';test('owner workbook maps all eight obvious roles and keeps extras', {skip:!fs.existsSync(fixture)},async()=>{const w=new ExcelJS.Workbook();await w.xlsx.readFile(fixture);const model=inspect(w.getWorksheet('Transactions'));model.columns=columns(model.rows,model.header);const r=suggestRoles(model,{selected:model.columns.map(c=>c.id),dateOrder:'dmy',numberStyle:'dot'});for(const [role,id]of Object.entries({Date:0,Reference:1,Description:3,Details:4,Category:5,Amount:10,Currency:11,Notes:18,Balance:16}))assert.equal(r.roles[role],id,role);for(const id of [2,6,7,8,9])assert.ok(!Object.values(r.roles).includes(id));assert.equal(model.rows.length-1,229);const data=prepare(model,{selected:model.columns.map(c=>c.id),roles:r.roles,reports:['Report Data','Inflows','Outflows'],period:'all',numberStyle:'dot',dateOrder:'dmy'});const amounts=model.rows.slice(1).map(row=>row[10]);const sum=values=>Math.round(values.reduce((a,b)=>a+b,0)*100)/100;assert.equal(data.totalIn,sum(amounts.filter(n=>n>0)));assert.equal(data.totalOut,sum(amounts.filter(n=>n<0)));assert.equal(data.net,sum(amounts));console.log(JSON.stringify({ownerRecords:data.records.length,totalIn:data.totalIn,totalOut:data.totalOut,net:data.net}));});

import {recognizeSource} from '../src/source-recognition.js';import {addMetadata} from '../src/report-import.js';
test('saved report metadata is validated and maps source IDs to physical positions',()=>{const w=new ExcelJS.Workbook();const s=w.addWorksheet('Report Data');s.addRows([['Amount','Date'],[12,'2025-01-01']]);const model={columns:[{id:8,key:'column_9',label:'Amount'},{id:2,key:'column_3',label:'Date'}]};addMetadata(w,model,{selected:[8,2],roles:{Amount:8,Date:2},period:'all',dateOrder:'dmy'});assert.deepEqual(recognizeSource(w).model.builder.roles,{Amount:0,Date:1});s.getCell('A1').value='Renamed';assert.equal(recognizeSource(w).model,undefined);assert.match(recognizeSource(w).warning,/could not be verified/);});
test('metadata without Amount preserves other valid mappings',()=>{const w=new ExcelJS.Workbook();w.addWorksheet('Report Data').addRows([['Date'],['2025-01-01']]);addMetadata(w,{columns:[{id:0,key:'column_1',label:'Date'}]},{selected:[0],roles:{Date:0},period:'all',dateOrder:'dmy'});assert.deepEqual(recognizeSource(w).model.builder.roles,{Date:0});});
test('reordered headings, punctuation and repeated candidates stay deterministic',()=>{const r=run(['NOTES','txn. date','Ref.','Amount'],[['hello','2025-01-01','R-1',10]]);assert.deepEqual(r.roles,{Date:1,Amount:3,Notes:0,Reference:2});assert.equal(run(['AMOUNT','amount'],[[10,12]]).roles.Amount,undefined);});
