
import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {SAMPLE_PATH} from './sample-path.js';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1')&&!r.url().startsWith('blob:'))requests.push(r.url());});
await page.goto(process.env.BF_BASE_URL||'http://127.0.0.1:5173');await page.locator('#navigation .behind-story').click();await page.locator('.experience').waitFor();
assert.match(await page.locator('.experience').innerText(),/July–September 2026/);await page.locator('[data-begin]').click();
await page.locator('[data-clean]').click();assert.equal(await page.locator('.story-columns span').count(),3);await page.locator('[data-separate]').click();assert.match(await page.locator('.experience-demo').innerText(),/Inflows/);await page.locator('[data-raw]').click();assert.equal(await page.locator('.story-columns span').count(),8);
await page.locator('[data-next]').click();
for(let i=0;i<7;i++){await page.locator('[data-tier="'+i+'"]').click();assert.match(await page.locator('.story-reveal').innerText(),/What changed/);}
await page.locator('[data-tier="3"]').click();await page.locator('[data-return]').click();assert.match(await page.locator('.story-reveal').innerText(),/recognized/);
await page.screenshot({path:'work/story-timeline-desktop.png'});
await page.locator('[data-next]').click();for(const person of ['Human experience','AI collaboration','Codex engineering']){await page.locator('[data-person="'+person+'"]').click();assert.equal(await page.locator('.experience-demo h3').innerText(),person);}
await page.locator('[data-next]').click();assert.match(await page.locator('.experience').innerText(),/does not file taxes/);
await page.locator('[data-next]').click();await page.locator('[data-route=guide]').click();await page.waitForFunction(()=>document.querySelector('.experience-header strong')?.textContent==='Business Flow Quick Guide');
await page.locator('[data-all]').click();while(await page.locator('[data-next]').isEnabled())await page.locator('[data-next]').click();await page.locator('[data-route=story]').click();await page.waitForFunction(()=>document.querySelector('.experience-header strong')?.textContent==='Behind Business Flow');
await page.locator('[data-replay]').click();await page.locator('[data-timeline]').click();
await page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});
for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.querySelector('.experience').scrollWidth>document.querySelector('.experience').clientWidth),false);const result=await page.evaluate(()=>axe.run(document.querySelector('.experience')));assert.deepEqual(result.violations.filter(x=>['serious','critical'].includes(x.impact)).map(x=>x.id),[]);}
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.story-reveal').evaluate(e=>getComputedStyle(e).animationName),'none');await page.screenshot({path:'work/story-timeline-mobile.png'});
await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.querySelector('.experience').contains(document.activeElement)));
await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});
await page.locator('.hero .start').click();await page.locator('#file').setInputFiles(SAMPLE_PATH);await page.locator('#header').waitFor();await page.locator('#next').click();const createBefore=await page.locator('#screen').innerHTML();
for(const cls of ['quick-guide','behind-story']){await page.locator('#navigation .'+cls).click();await page.locator('.experience').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('#screen').innerHTML(),createBefore);}
await page.locator('#navigation .behind-story').focus();await page.keyboard.press('Enter');await page.locator('.experience').waitFor();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('behind-story')),true);
await page.reload();await page.locator('.entry-paths .explore-existing').click();await page.locator('#existing-file').setInputFiles('work/builder-processed-report.xlsx');await page.waitForFunction(()=>document.getElementById('live-status')?.textContent.includes('Updated locally.'));
await page.locator('#live-mode').selectOption('one');await page.waitForFunction(()=>document.getElementById('live-status')?.textContent.includes('Updated locally.'));await page.locator('#live-value-list input').first().check();await page.waitForFunction(()=>document.getElementById('live-status')?.textContent.includes('Updated locally.'));const liveBefore=await page.locator('.live-kpis').innerText(),filterBefore=await page.locator('#live-filter-summary').innerText();for(const cls of ['quick-guide','behind-story']){await page.locator('#navigation .'+cls).click();await page.locator('.experience').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.live-kpis').innerText(),liveBefore);assert.equal(await page.locator('#live-filter-summary').innerText(),filterBefore);}
await page.reload();await page.locator('.build-workbook').click();await page.locator('#builder-next').click();const builderBefore=await page.locator('#builder').innerHTML();await page.locator('#navigation .behind-story').click();await page.locator('.experience').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('#builder').innerHTML(),builderBefore);await page.reload();await page.locator('#login').click();assert(await page.locator('#auth').isVisible());await page.locator('#close-auth').click();
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await browser.close();console.log('PASS Story origin, before/after, all tiers, collaboration, crosslinks, mobile, axe, reduced motion, keyboard, Create/Live preservation, login, no external requests.');
