import {date} from './engine.js';
export const TIME_LEVELS=['auto','day','week','month','quarter','year'];
export function bucket(day,level){if(!day)return 'Invalid date';const [y,m]=day.split('-').map(Number);if(level==='month')return day.slice(0,7);if(level==='quarter')return `${y} Q${Math.ceil(m/3)}`;if(level==='year')return String(y);if(level==='week'){const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10)+' (week)';}return day;}
function accumulator(){return {totalIn:0,totalOut:0,net:0,inCount:0,outCount:0,count:0,validAmounts:0,largestIn:null,largestOut:null,first:null,last:null,days:new Set(),ci:0,co:0};}
function add(a,r){a.count++;if(r.day){a.days.add(r.day);if(!a.first||r.day<a.first)a.first=r.day;if(!a.last||r.day>a.last)a.last=r.day;}if(r.amount==null)return;a.validAmounts++;if(r.amount>0){const y=r.amount-a.ci,t=a.totalIn+y;a.ci=(t-a.totalIn)-y;a.totalIn=t;a.inCount++;a.largestIn=a.largestIn==null?r.amount:Math.max(a.largestIn,r.amount);}if(r.amount<0){const y=r.amount-a.co,t=a.totalOut+y;a.co=(t-a.totalOut)-y;a.totalOut=t;a.outCount++;a.largestOut=a.largestOut==null?r.amount:Math.min(a.largestOut,r.amount);}}
function finish(a){return {...a,days:undefined,ci:undefined,co:undefined,net:a.totalIn+a.totalOut,averageIn:a.inCount?a.totalIn/a.inCount:null,averageOut:a.outCount?a.totalOut/a.outCount:null,average:a.validAmounts?(a.totalIn+a.totalOut)/a.validAmounts:null,ratio:a.totalOut?a.totalIn/Math.abs(a.totalOut):null,margin:a.totalIn?(a.totalIn+a.totalOut)/a.totalIn:null,activeDays:a.days.size,averagePerDay:a.days.size?a.count/a.days.size:null};}
export function currency(r,c){const i=c.roles.Currency;return i==null?'Source units':String(r.values[i]??'').trim()||'No currency';}
export function groupValue(r,g,c){let value=r.values[g.column];if(g.column===c.roles.Date){const d=r.day??date(value,c.dateOrder);return {key:d?`date:${bucket(d,g.dateLevel||'day')}`:'invalid-date',label:d?bucket(d,g.dateLevel||'day'):'Invalid date'};}if(g.column===c.roles.Amount&&r.amount!=null)value=r.amount;if(value instanceof Date)value=value.toISOString().slice(0,10);if(value==null||(typeof value==='string'&&!value.trim()))return {key:'blank:',label:'No value'};if(typeof value==='string')value=value.trim();return {key:`${typeof value}:${value}`,label:value};}
export function discover(records,g,c){const values=new Map();for(const r of records){const v=groupValue(r,g,c);if(!values.has(v.key))values.set(v.key,v);}return [...values.values()].sort((a,b)=>String(a.label).localeCompare(String(b.label),undefined,{numeric:true}));}
export function grouped(records,g,c){const groups=new Map(),selected=new Set(g.values||[]);for(const r of records){const v=groupValue(r,g,c);if(g.mode&&g.mode!=='all'&&!selected.has(v.key))continue;const curr=currency(r,c),key=JSON.stringify([curr,v.key]);if(!groups.has(key))groups.set(key,{...accumulator(),key:v.key,label:v.label,currency:curr});add(groups.get(key),r);}const rows=[...groups.values()].map(finish);const field=g.sort||'label',direction=g.direction==='desc'?-1:1;return rows.sort((a,b)=>{const curr=a.currency.localeCompare(b.currency);if(curr)return curr;const diff=field==='label'?String(a.label).localeCompare(String(b.label),undefined,{numeric:true}):a[field]-b[field];return direction*diff;});}
export function validateGroups(model,c){if(!c.reports.includes('Analysis'))return;for(const g of c.groups||[]){if(!model.columns.some(col=>col.id===g.column))throw Error('Choose a source column for every group analysis.');if(g.mode==='one'&&g.values?.length!==1)throw Error('Choose exactly one value for One Value mode.');if(g.mode==='selected'&&!g.values?.length)throw Error('Choose at least one value for Selected Values mode.');}}
export function analyze(model,c,data){validateGroups(model,c);const sections=new Map(),days=data.records.filter(r=>r.day).map(r=>r.day).sort();const span=days.length?(Date.parse(days.at(-1))-Date.parse(days[0]))/86400000:0;const level=c.timeGrouping&&c.timeGrouping!=='auto'?c.timeGrouping:(span<=45?'day':span>730?'quarter':'month');for(const r of data.records){const curr=currency(r,c);if(!sections.has(curr))sections.set(curr,{currency:curr,summary:accumulator(),time:new Map(),invalidDates:0,topIn:[],topOut:[]});const s=sections.get(curr);add(s.summary,r);if(r.day){const key=bucket(r.day,level);if(!s.time.has(key))s.time.set(key,{...accumulator(),label:key});add(s.time.get(key),r);}else if(c.roles.Date!=null)s.invalidDates++;if(r.amount>0){s.topIn.push(r);s.topIn.sort((a,b)=>b.amount-a.amount);s.topIn.length=Math.min(5,s.topIn.length);}if(r.amount<0){s.topOut.push(r);s.topOut.sort((a,b)=>a.amount-b.amount);s.topOut.length=Math.min(5,s.topOut.length);}}
const groups=(c.groups||[]).map(g=>({...g,header:model.columns.find(x=>x.id===g.column).label,columnKey:model.columns.find(x=>x.id===g.column).key,rows:grouped(data.records,g,c)}));const insightColumn=(c.groups||[])[0]?.column??c.roles.Category??c.roles.Description??c.roles.Details;const insights=insightColumn==null?[]:grouped(data.records,{column:insightColumn,mode:'all'},c);return {timeGrouping:level,amountAvailable:c.roles.Amount!=null,dateAvailable:c.roles.Date!=null,groups,sections:[...sections.values()].map(s=>{const rows=insights.filter(r=>r.currency===s.currency),time=[...s.time.values()].map(finish).sort((a,b)=>a.label.localeCompare(b.label));return {...s,summary:finish(s.summary),time,insightHeader:insightColumn==null?null:model.columns.find(x=>x.id===insightColumn).label,rankings:{inflows:rows.filter(r=>r.totalIn>0).sort((a,b)=>b.totalIn-a.totalIn).slice(0,5),outflows:rows.filter(r=>r.totalOut<0).sort((a,b)=>a.totalOut-b.totalOut).slice(0,5),positive:rows.filter(r=>r.net>0).sort((a,b)=>b.net-a.net).slice(0,5),negative:rows.filter(r=>r.net<0).sort((a,b)=>a.net-b.net).slice(0,5)}};})};}
export function safeSheetName(header,used){const base=('Group - '+header).replace(/[\\/*?:\[\]\x00-\x1f]/g,' ').replace(/^'+|'+$/g,'').slice(0,31)||'Group';let name=base,n=2;while(used.has(name.toLowerCase())){const suffix=' '+n++;name=base.slice(0,31-suffix.length)+suffix;}used.add(name.toLowerCase());return name;}

