import {safeSheetName} from './analysis.js';
const money='#,##0.00;[Red]-#,##0.00';
const border={top:{style:'thin',color:{argb:'FFD7E2DA'}},bottom:{style:'thin',color:{argb:'FFD7E2DA'}},left:{style:'thin',color:{argb:'FFD7E2DA'}},right:{style:'thin',color:{argb:'FFD7E2DA'}}};
function text(s,row,col,value,bold=false){const cell=s.getCell(row,col);cell.value=value??'N/A';cell.font={name:'Calibri',size:11,bold,color:{argb:'FF163D36'}};cell.alignment={vertical:'middle',wrapText:true};return cell;}
function heading(s,row,title){s.mergeCells(row,1,row,12);text(s,row,1,title,true).font.size=15;s.getRow(row).height=32;}
function table(s,row,headers,rows){headers.forEach((h,i)=>{const cell=text(s,row,i+1,h,true);cell.font.color={argb:'FFFFFFFF'};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF163D36'}};cell.border=border;});s.getRow(row).height=36;rows.forEach((values,index)=>{values.forEach((v,i)=>{const cell=text(s,row+index+1,i+1,v);cell.border=border;if(typeof v==='number')cell.numFmt=money;if(index%2===0)cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF0F6F3'}};});s.getRow(row+index+1).height=40;});return row+rows.length+2;}
const formula=(name,col,start,end)=>`'${name.replaceAll("'","''")}'!$${col}$${start}:$${col}$${end}`;
const periodLabel=c=>c.period==='custom'?`${c.start} to ${c.end}`:c.period||'all';
const metricDefinitions=[['Total Inflows','totalIn'],['Total Outflows','totalOut'],['Net Flow','net'],['Total Transactions','count'],['Inflow Transactions','inCount'],['Outflow Transactions','outCount'],['Average Inflow','averageIn'],['Average Outflow','averageOut'],['Largest Inflow','largestIn'],['Largest Outflow','largestOut'],['Inflow / Outflow Ratio','ratio'],['Net Flow Margin','margin']];
function base(s){for(let i=1;i<=12;i++)s.getColumn(i).width=16;s.views=[{state:'frozen',ySplit:3,showGridLines:false}];s.properties.defaultRowHeight=21;s.pageSetup={orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0};s.pageMargins={left:.3,right:.3,top:.5,bottom:.5,header:.2,footer:.2};}
export function addAnalysisSheets(w,model,c,data,analysis,charts){const s=w.addWorksheet('Analysis');base(s);let row=1;heading(s,row,'DeTleng Business Flow | Executive Analysis');row+=2;heading(s,row,`Period: ${periodLabel(c)} · ${data.records.length} transactions`);row+=2;if(data.invalid||data.blank){heading(s,row,`${data.invalid} invalid and ${data.blank} blank amounts excluded from monetary calculations; retained in record counts.`);row+=2;}if(analysis.sections.length>1){heading(s,row,'Currencies are analyzed separately. No conversion or combined monetary total.');row+=2;}
for(const section of analysis.sections){heading(s,row,`Business overview — ${section.currency}`);row+=2;const k=section.summary,defs=analysis.amountAvailable?metricDefinitions:[['Total Transactions','count']];defs.forEach(([label,key],index)=>{const col=1+(index%4)*3,r=row+Math.floor(index/4)*3;s.mergeCells(r,col,r,col+2);text(s,r,col,label,true);s.getRow(r).height=28;s.mergeCells(r+1,col,r+1,col+2);const cell=text(s,r+1,col,k[key]);cell.font.size=18;cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFEAF3E6'}};cell.numFmt=key==='margin'?'0.00%':['count','inCount','outCount'].includes(key)?'0':key==='ratio'?'0.00"×"':money;s.getRow(r+1).height=34;});row+=Math.ceil(defs.length/4)*3+1;
if(k.first){heading(s,row,`First transaction: ${k.first} | Last: ${k.last}`);row++;heading(s,row,`Active transaction days: ${k.activeDays} | Average transactions per active day: ${k.averagePerDay.toFixed(2)}`);row+=2;}if(!analysis.amountAvailable){heading(s,row,'Map Amount to include monetary KPIs and charts.');row+=2;}
let timeStart,timeEnd;if(section.time.length){heading(s,row,`Time summary — ${analysis.timeGrouping}`);row++;timeStart=row+1;timeEnd=row+section.time.length;row=table(s,row,['Period','Inflows','Outflows','Net Flow','Inflow Count','Outflow Count','Total Transactions'],section.time.map(t=>[t.label,analysis.amountAvailable?t.totalIn:null,analysis.amountAvailable?t.totalOut:null,analysis.amountAvailable?t.net:null,t.inCount,t.outCount,t.count]));for(let r=timeStart;r<=timeEnd;r++)for(let col=5;col<=7;col++)s.getCell(r,col).numFmt='0';if(section.invalidDates){heading(s,row,`${section.invalidDates} records with unreadable dates are excluded from the time summary.`);row+=2;}}else{heading(s,row,analysis.dateAvailable?'No valid dates: time summary and Net Flow Trend unavailable.':'Map Date to include time summary and Net Flow Trend.');row+=2;}
if(analysis.amountAvailable){const chartRow=row;let labels,start,end,cat,inCol,outCol;if(section.time.length){labels=section.time.map(t=>t.label);start=timeStart;end=timeEnd;cat='A';inCol='B';outCol='H';text(s,timeStart-1,8,'Outflow magnitude (chart)');section.time.forEach((t,i)=>text(s,timeStart+i,8,Math.abs(t.totalOut)));}else{start=row;end=row+1;labels=['Inflows','Outflows'];text(s,start,1,'Inflows');text(s,start,2,k.totalIn);text(s,end,1,'Outflows');text(s,end,2,Math.abs(k.totalOut));cat='A';inCol='B';row+=3;}
const bar={sheetId:s.id,type:'bar',title:'Inflows vs Outflows (absolute outflow magnitude)',row:row,col:0,categoryFormula:formula(s.name,cat,start,end),labels,series:section.time.length?[{name:'Inflows',formula:formula(s.name,inCol,start,end),values:section.time.map(t=>t.totalIn)},{name:'Outflows (absolute)',formula:formula(s.name,outCol,start,end),values:section.time.map(t=>Math.abs(t.totalOut))}]:[{name:'Flow magnitude',formula:formula(s.name,'B',start,end),values:[k.totalIn,Math.abs(k.totalOut)]}]};charts.push(bar);if(section.time.length)charts.push({sheetId:s.id,type:'line',title:'Net Flow Trend',row:row,col:6,labels,categoryFormula:formula(s.name,'A',timeStart,timeEnd),series:[{name:'Net Flow',formula:formula(s.name,'D',timeStart,timeEnd),values:section.time.map(t=>t.net)}]});row+=18;const mixRow=row;text(s,mixRow,1,'Inflows');text(s,mixRow,2,k.totalIn);text(s,mixRow+1,1,'Outflows (absolute)');text(s,mixRow+1,2,Math.abs(k.totalOut));row+=3;if(k.totalIn||k.totalOut){charts.push({sheetId:s.id,type:'doughnut',title:'Flow Mix',row,col:0,labels:['Inflows','Outflows'],categoryFormula:formula(s.name,'A',mixRow,mixRow+1),series:[{name:'Flow Mix',formula:formula(s.name,'B',mixRow,mixRow+1),values:[k.totalIn,Math.abs(k.totalOut)]}]});row+=18;}else{heading(s,row,'Flow Mix: no nonzero amounts to chart.');row+=2;}}
if(section.time.length&&analysis.amountAvailable){heading(s,row,'Period highlights');row++;const sort=(field,ascending=false)=>[...section.time].sort((a,b)=>ascending?a[field]-b[field]:b[field]-a[field])[0];row=table(s,row,['Business question','Period','Value'],[['Best Net Flow Period',sort('net').label,sort('net').net],['Highest Inflow Period',sort('totalIn').label,sort('totalIn').totalIn],['Highest Outflow Period',sort('totalOut',true).label,sort('totalOut',true).totalOut],['Most Active Period',sort('count').label,sort('count').count]]);}
if(section.insightHeader&&analysis.amountAvailable){for(const [key,title,field]of [['inflows','Top 5 Inflow Groups','totalIn'],['outflows','Top 5 Outflow Groups','totalOut'],['positive','Top 5 Net Positive Groups','net'],['negative','Top 5 Net Negative Groups','net']]){heading(s,row,`${title} — ${section.insightHeader}`);row++;row=table(s,row,[section.insightHeader,'Amount','Transactions'],section.rankings[key].map(g=>[g.label,g[field],g.count]));}}
for(const [list,title]of [[section.topIn,'Largest Inflow Transactions'],[section.topOut,'Largest Outflow Transactions']]){if(!list.length)continue;heading(s,row,title);row++;const descriptive=c.roles.Description??c.roles.Details??c.roles.Reference;row=table(s,row,['Date',descriptive==null?'Transaction':model.columns.find(x=>x.id===descriptive).label,'Amount'],list.map(r=>[r.day??'N/A',descriptive==null?'Source transaction':r.values[descriptive],r.amount]));}row+=3;}
s.pageSetup.printArea=`A1:L${row}`;const used=new Set(w.worksheets.map(sheet=>sheet.name.toLowerCase()));for(const group of analysis.groups){const gs=w.addWorksheet(safeSheetName(group.header,used));base(gs);heading(gs,1,`Grouped by: ${group.header}`);heading(gs,3,`Period: ${periodLabel(c)} | Mode: ${group.mode||'all'} | Level: ${group.dateLevel||'exact value'}`);heading(gs,5,`Included values: ${group.mode==='all'?'All Values':group.rows.map(g=>g.label).filter((v,i,a)=>a.indexOf(v)===i).join(', ')||'No matching values'}`);const headers=[group.header,'Currency','Inflows','Outflows','Net Flow','Inflow Count','Outflow Count','Total Transactions','Average Transaction','Largest Inflow','Largest Outflow'];if(analysis.dateAvailable)headers.push('First Transaction','Last Transaction');const rows=group.rows.map(g=>[g.label,g.currency,analysis.amountAvailable?g.totalIn:null,analysis.amountAvailable?g.totalOut:null,analysis.amountAvailable?g.net:null,g.inCount,g.outCount,g.count,analysis.amountAvailable?g.average:null,g.largestIn,g.largestOut,...(analysis.dateAvailable?[g.first,g.last]:[])]);let end=table(gs,7,headers,rows);headers.forEach((_,i)=>gs.getColumn(i+1).width=i===0?32:i===1?18:18);for(let r=8;r<8+rows.length;r++)for(let col=6;col<=8;col++)gs.getCell(r,col).numFmt='0';if(group.chart&&analysis.amountAvailable){for(const curr of new Set(group.rows.map(g=>g.currency))){const top=group.rows.filter(g=>g.currency===curr).sort((a,b)=>b.net-a.net).slice(0,10);if(!top.length)continue;heading(gs,end,`Top 10 Groups by Net Flow — ${curr}`);end++;const start=end+1;end=table(gs,end,[group.header,'Net Flow'],top.map(g=>[g.label,g.net]));charts.push({sheetId:gs.id,type:'bar',horizontal:true,title:`Top 10 Groups by Net Flow — ${curr}`,row:end,width:8,labels:top.map(g=>g.label),categoryFormula:formula(gs.name,'A',start,start+top.length-1),series:[{name:'Net Flow',formula:formula(gs.name,'B',start,start+top.length-1),values:top.map(g=>g.net)}]});end+=18;}}gs.pageSetup.printArea=`A1:M${end}`;group.sheetName=gs.name;}}

