import './builder.css';
import {definition,TEMPLATES,TYPES,CAPACITIES,DATE_FORMATS,CURRENCIES,selected,addColumn,validateDefinition,sampleRange} from './builder-schema.js';
import {ROLES} from './engine.js';
import {WorkbookClient} from './workbook-client.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=(items,current)=>items.map(x=>`<option value="${esc(x)}" ${String(x)===String(current)?'selected':''}>${esc(x)}</option>`).join('');
const steps=['Workbook Type','Columns','Field Setup','Workbook Settings','Review','Choose Output'];
export function workbookBuilder(host,{home,use,create}){
 let d=definition(),step=0,busy=false,stage='',result=null,url=null,closed=false;
 const $=id=>host.querySelector(`#${id}`);
 const client=new WorkbookClient(({data:m})=>{if(closed)return;if(m.type==='progress'){stage=m.stage;const p=$('builder-stage');if(p)p.textContent=stage;}if(m.type==='error'){busy=false;render();error(m.message);}if(m.type==='builder-result'){busy=false;result=m;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(new Blob([m.buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));render();focus();}},message=>{busy=false;render();error(message);},{timeout:120000,createWorker:()=>new Worker(new URL('./builder-worker.js',import.meta.url),{type:'module'})});
 function error(message){$('builder-error').hidden=false;$('builder-error').textContent=message;$('builder-error').focus();}
 function focus(){const h=host.querySelector('h2');if(h){h.tabIndex=-1;h.focus();}host.scrollIntoView({block:'start'});}
 function controls(){return `<div class="controls"><button id="builder-back">← Back</button>${step<5?'<button id="builder-next" class="primary">Continue →</button>':''}</div>`;}
 function field(c,i){return `<article class="builder-field" data-field="${esc(c.id)}"><div class="builder-field-title"><strong>${esc(c.label)}</strong><span class="help">${c.recommended?'Recommended · ':''}${esc(c.type)}</span></div><div class="builder-field-grid"><div><label for="b-label-${i}">Visible heading</label><input id="b-label-${i}" data-property="label" maxlength="100" value="${esc(c.label)}"></div><div><label for="b-type-${i}">Field type</label><select id="b-type-${i}" data-property="type">${options(TYPES,c.type)}</select></div><div><label for="b-role-${i}">Business Flow role</label><select id="b-role-${i}" data-property="role"><option value="">No role</option>${options(ROLES,c.role)}</select></div><label class="builder-check"><input type="checkbox" data-property="required" ${c.required?'checked':''}> Required field</label></div><details><summary>Dropdown validation</summary><label for="b-list-${i}">Allowed values, one per line (leave empty for flexible entry)</label><textarea id="b-list-${i}" data-property="validation" rows="3">${esc(c.validation.join('\n'))}</textarea></details><div class="actions"><button data-move="up" ${d.columns.indexOf(c)===0?'disabled':''} aria-label="Move ${esc(c.label)} up">↑ Move up</button><button data-move="down" ${d.columns.indexOf(c)===d.columns.length-1?'disabled':''} aria-label="Move ${esc(c.label)} down">↓ Move down</button><button data-remove aria-label="Remove ${esc(c.label)}">Remove column</button></div></article>`;}
 function preview(){return `<aside class="builder-structure" aria-label="Workbook structure preview"><b>Workbook structure</b><div>${selected(d).map(c=>`<span>${esc(c.label)} <small>${esc(c.type)}</small></span>`).join('')||'<p>No columns selected.</p>'}</div></aside>`;}
 function render(){
  let body='';
  if(busy)body=`<h2>Building your ${result?.mode||'business'} workbook.</h2><div class="loading-status"><span class="activity" aria-hidden="true"></span><p id="builder-stage" role="status">${esc(stage)}</p></div><progress aria-label="Building workbook"></progress><p>Your workbook is built locally on this device.</p><button id="builder-cancel">Cancel generation</button>`;
  else if(result){const sample=result.mode==='sample';body=`<p class="eyebrow">Ready when you are ✓</p><h2>Your ${sample?'sample':'blank'} business workbook is ready.</h2>${sample?'<p class="alert">Sample data — generated for demonstration and testing. Not real business records.</p>':'<p>Fill this workbook with your real business data and return to Business Flow whenever you are ready to create reports and Live Analytics.</p>'}<p>${esc(result.name)} · ${result.metadata.columns.length} columns · ${result.metadata.rowCapacity.toLocaleString()} ${sample?'sample records':'prepared data-entry rows'}</p><div class="actions">${sample?'<button id="builder-use" class="primary">Use in Business Flow →</button>':''}<a id="builder-download" class="button ${sample?'':'primary'}" href="${url}" download="${esc(result.name)}">Download ${sample?'Sample':'Blank'} Workbook</a><button id="builder-another">Build Another Workbook</button><button id="builder-adjust">Adjust this workbook</button></div>${sample?`<h3>A small preview of your sample data</h3><div class="table-wrap" tabindex="0" aria-label="Sample records preview"><table><thead><tr>${result.metadata.columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${result.preview.map(r=>`<tr>${r.map(v=>`<td>${esc(v instanceof Date?v.toISOString().slice(0,10):v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="help">Preview shows 10 records. The workbook contains every generated record.</p>`:''}`;}
  else if(step===0)body=`<h2>What kind of workbook do you need?</h2><p>A useful starting point. Make it your own in the next steps.</p><div class="builder-templates">${TEMPLATES.map(t=>`<label class="builder-template"><input type="radio" name="builder-template" value="${t.id}" ${d.templateId===t.id?'checked':''}><span><strong>${esc(t.name)}</strong><small>${esc(t.purpose)}</small></span></label>`).join('')}</div>`;
  else if(step===1)body=`<h2>Choose your business fields.</h2><p>Recommended fields are already selected. Keep the fields that matter to you.</p><div class="actions"><button id="builder-recommended">Select Recommended</button><button id="builder-all">Select All</button><button id="builder-optional">Clear Optional</button></div>${d.columns.map(c=>`<label class="choice"><input type="checkbox" data-select="${esc(c.id)}" ${c.selected?'checked':''}><span><b>${esc(c.label)}</b><small>${esc(c.type)} · ${c.recommended?'Recommended':'Optional'}${c.role?' · '+esc(c.role)+' role':''}</small></span></label>`).join('')}<button id="builder-add">+ Add Column</button>`;
  else if(step===2)body=`<h2>Make the fields yours.</h2><p>Rename headings, confirm types and roles, or move fields into the order you prefer. Each role can be assigned once.</p><div class="builder-fields">${selected(d).map(field).join('')}</div><button id="builder-add">+ Add Column</button>`;
  else if(step===3)body=`<h2>A few practical details.</h2><div class="builder-settings"><div><label for="builder-name">Workbook name</label><input id="builder-name" maxlength="100" value="${esc(d.workbookName)}"></div><div><label for="builder-capacity-choice">Rows / record capacity</label><select id="builder-capacity-choice">${options([...CAPACITIES,'Custom'],CAPACITIES.includes(d.rowCapacity)?d.rowCapacity:'Custom')}</select><label for="builder-capacity">Exact row count (100–5,000)</label><input id="builder-capacity" type="number" min="100" max="5000" step="1" value="${d.rowCapacity}"></div><div><label for="builder-date">Date display</label><select id="builder-date">${options(DATE_FORMATS,d.dateFormat)}</select></div><div><label for="builder-number">Text number input convention</label><select id="builder-number"><option value="dot" ${d.numberStyle==='dot'?'selected':''}>1,234.56 — decimal point</option><option value="comma" ${d.numberStyle==='comma'?'selected':''}>1.234,56 — decimal comma</option></select></div><div><label for="builder-currency">Default currency</label><select id="builder-currency">${options(CURRENCIES,d.currency)}</select></div></div><p class="help">Blank: prepared data-entry capacity. Sample: actual generated records. Numeric Excel cells stay numeric; Excel uses your regional separators. The text convention helps Business Flow read any amounts you later enter as text. No currency conversion.</p>`;
  else if(step===4)body=`<h2>Your structure, ready to use.</h2><dl class="review"><dt>Workbook</dt><dd>${esc(d.workbookName)}</dd><dt>Template</dt><dd>${esc(TEMPLATES.find(t=>t.id===d.templateId).name)}</dd><dt>Columns</dt><dd>${selected(d).length}</dd><dt>Rows / capacity</dt><dd>${d.rowCapacity.toLocaleString()}</dd><dt>Date display</dt><dd>${esc(d.dateFormat)}</dd><dt>Currency</dt><dd>${esc(d.currency)}</dd><dt>Mapped roles</dt><dd>${selected(d).filter(c=>c.role).map(c=>esc(c.role)+' → '+esc(c.label)).join(', ')||'None'}</dd></dl><p class="alert">${selected(d).some(c=>c.role==='Amount')?'Business Flow-ready ✓':'Workbook can be generated, but monetary Live Analytics will require an Amount field.'}</p><div class="actions"><button id="builder-edit-columns">Edit Columns</button><button id="builder-edit-settings">Edit Settings</button></div>`;
  else body=`<h2>Two ways to start.</h2><p>The same structure, built for your next step.</p><div class="builder-output-grid"><article><h3>A blank workbook for real business</h3><p>${d.rowCapacity.toLocaleString()} prepared rows with formats, dropdowns and roles. No sample transactions.</p><button id="builder-blank" class="primary">Generate Blank Workbook</button></article><article><h3>A sample workbook to explore</h3><p>${d.rowCapacity.toLocaleString()} realistic synthetic records. Experience reports and analytics right away.</p><label for="builder-period">Sample period</label><select id="builder-period"><option value="1" ${+d.sampleMonths===1?'selected':''}>1 Month</option><option value="3" ${+d.sampleMonths===3?'selected':''}>3 Months</option><option value="6" ${+d.sampleMonths===6?'selected':''}>6 Months</option><option value="12" ${+d.sampleMonths===12?'selected':''}>12 Months</option><option value="custom" ${d.sampleMonths==='custom'?'selected':''}>Custom Range</option></select>${d.sampleMonths==='custom'?`<label for="builder-start">Start date</label><input id="builder-start" type="date" value="${esc(d.sampleStart)}"><label for="builder-end">End date</label><input id="builder-end" type="date" value="${esc(d.sampleEnd)}">`:'<p class="help">Calendar months ending in the current month.</p>'}<p class="help">Sample data — generated for demonstration and testing. Not real business records.</p><button id="builder-sample" class="primary">Generate Sample Workbook</button></article></div>`;
  host.innerHTML=`<div class="workspace-heading"><div><p class="eyebrow">Your workbook workshop</p><h1>Build a good beginning.</h1></div><span class="pill">Local processing ✓</span></div><div class="actions builder-top"><button id="builder-home">Back to Home</button><button id="builder-over">Start Over</button><button id="builder-create">Create Report</button></div><ol class="builder-steps" aria-label="Workbook builder progress">${steps.map((s,i)=>`<li ${!result&&i===step?'aria-current="step"':''}>${i+1} ${s}</li>`).join('')}</ol><div class="panel" aria-busy="${busy}"><div id="builder-error" class="alert" role="alert" tabindex="-1" hidden></div>${body}${!busy&&!result?preview():''}${!busy&&!result?controls():''}</div>`;
  bind();
 }
 function bind(){
  $('builder-home').onclick=home;$('builder-create').onclick=create;$('builder-over').onclick=()=>{client.cancel();busy=false;if(url)URL.revokeObjectURL(url);url=null;result=null;d=definition();step=0;render();focus();};
  if($('builder-next'))$('builder-next').onclick=()=>{try{if(step>0)validateDefinition(d);step++;render();focus();}catch(e){error(e.message);}};
  if($('builder-back')){$('builder-back').disabled=step===0;$('builder-back').onclick=()=>{step--;render();focus();};}
  host.querySelectorAll('[name=builder-template]').forEach(input=>input.onchange=()=>{d=definition(input.value);render();host.querySelector('[name=builder-template]:checked').focus();});
  host.querySelectorAll('[data-select]').forEach(input=>input.onchange=()=>{d.columns.find(c=>c.id===input.dataset.select).selected=input.checked;const p=host.querySelector('.builder-structure');p.outerHTML=preview();});
  for(const [id,fn]of [['builder-recommended',c=>c.recommended],['builder-all',()=>true],['builder-optional',c=>c.selected&&c.recommended]])if($(id))$(id).onclick=()=>{d.columns.forEach(c=>c.selected=!!fn(c));render();};
  if($('builder-add'))$('builder-add').onclick=()=>{if(d.columns.length>=64){error('This version supports up to 64 fields.');return;}addColumn(d);render();};
  host.querySelectorAll('[data-field]').forEach(article=>{const c=d.columns.find(c=>c.id===article.dataset.field);article.querySelectorAll('[data-property]').forEach(input=>input.onchange=()=>{c[input.dataset.property]=input.dataset.property==='required'?input.checked:input.dataset.property==='validation'?input.value.split('\n').map(x=>x.trim()).filter(Boolean):input.value;const p=host.querySelector('.builder-structure');if(p)p.outerHTML=preview();});article.querySelectorAll('[data-move]').forEach(button=>button.onclick=()=>{const i=d.columns.indexOf(c),j=i+(button.dataset.move==='up'?-1:1);[d.columns[i],d.columns[j]]=[d.columns[j],d.columns[i]];render();const moved=host.querySelector(`[data-field="${c.id}"] [data-move="${button.dataset.move}"]`);(moved.disabled?host.querySelector(`[data-field="${c.id}"] [data-property=label]`):moved).focus();});article.querySelector('[data-remove]').onclick=()=>{d.columns.splice(d.columns.indexOf(c),1);render();};});
  if($('builder-capacity-choice'))$('builder-capacity-choice').onchange=e=>{if(e.target.value!=='Custom'){d.rowCapacity=+e.target.value;$('builder-capacity').value=d.rowCapacity;}else $('builder-capacity').focus();};
  for(const [id,key,numeric]of [['builder-name','workbookName'],['builder-capacity','rowCapacity',true],['builder-date','dateFormat'],['builder-number','numberStyle'],['builder-currency','currency'],['builder-start','sampleStart'],['builder-end','sampleEnd']])if($(id))$(id).onchange=e=>{d[key]=numeric?+e.target.value:e.target.value;};
  if($('builder-period'))$('builder-period').onchange=e=>{d.sampleMonths=e.target.value==='custom'?'custom':+e.target.value;render();$('builder-period').focus();};
  for(const [id,s]of [['builder-edit-columns',1],['builder-edit-settings',3]])if($(id))$(id).onclick=()=>{step=s;render();focus();};
  for(const mode of ['blank','sample'])if($(`builder-${mode}`))$(`builder-${mode}`).onclick=()=>{try{validateDefinition(d);if(mode==='sample')sampleRange(d);busy=true;stage='Building workbook structure…';render();client.send({type:'build',definition:d,mode});}catch(e){busy=false;error(e.message);}};
  if($('builder-cancel'))$('builder-cancel').onclick=()=>{client.cancel();busy=false;render();error('Generation canceled. Adjust your settings or try again.');};
  if($('builder-use'))$('builder-use').onclick=()=>use(result.model,result.name,result.buffer.byteLength);
  if($('builder-another'))$('builder-another').onclick=$('builder-over').onclick;
  if($('builder-adjust'))$('builder-adjust').onclick=()=>{result=null;if(url)URL.revokeObjectURL(url);url=null;step=4;render();focus();};
 }
 render();focus();return {close(){closed=true;client.cancel();if(url)URL.revokeObjectURL(url);url=null;result=null;host.innerHTML='';}};
}
