import {WorkbookClient} from './workbook-client.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function existingReport(host,{ready,create}={}){
  let file,sequence=0,closed=false,detected,blobUrl;
  const client=new WorkbookClient(message=>{const m=message.data;if(m.type==='progress'){host.querySelector('#existing-status').textContent=m.stage;}if(m.type==='error')fail(m.message);if(m.type==='existing-detected'){detected=m.detected;confirm();}if(m.type==='existing-ready'){client.cancel();ready(m.dataset,blobUrl,file.name);}},fail);
  function fail(message){if(closed)return;host.querySelector('#existing-status').textContent=message;host.querySelector('#existing-status').setAttribute('role','alert');host.querySelector('#existing-busy').hidden=true;host.querySelector('#existing-file').disabled=false;host.querySelector('#existing-cancel').hidden=true;}
  function load(selected){if(!selected)return;if(!/\.xlsx$/i.test(selected.name))return fail('Choose an .xlsx Business Flow report.');if(selected.size>20*1024*1024)return fail('Choose a report smaller than 20 MB.');file=selected;detected=null;const token=++sequence;client.cancel();if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=URL.createObjectURL(file);host.querySelector('#existing-status').textContent='Reading Business Flow report locally…';host.querySelector('#existing-status').setAttribute('role','status');host.querySelector('#existing-busy').hidden=false;host.querySelector('#existing-cancel').hidden=false;host.querySelector('#existing-file').disabled=true;selected.arrayBuffer().then(buffer=>{if(closed||sequence!==token)return;client.send({type:'existing-load',buffer,name:file.name},[buffer]);}).catch(()=>fail('This file could not be read. Choose another unencrypted workbook.'));}
  function confirm(){host.querySelector('#existing-file').disabled=false;host.querySelector('#existing-busy').hidden=true;host.querySelector('#existing-cancel').hidden=true;host.querySelector('#existing-status').textContent='Compatible Business Flow report found. Confirm the columns below.';
    const columnOptions=detected.columns.map(c=>`<option value="${c.id}">${esc(c.label)} · column ${c.id+1}</option>`).join('');
    host.querySelector('#existing-confirm').innerHTML=`<h3>Confirm your report’s meaning.</h3><p>Older reports do not store role mappings. Choose Amount explicitly; Date and other roles are optional.</p>${detected.warning?`<p class="alert">${esc(detected.warning)}</p>`:''}<div class="grid">${['Amount','Date','Description','Currency'].map(role=>`<div><label for="existing-${role}">${role}${role==='Amount'?' (required)':' (optional)'}</label><select id="existing-${role}"><option value="">${role==='Amount'?'Choose Amount':'No role'}</option>${columnOptions}</select></div>`).join('')}<div><label for="existing-number">Text number format</label><select id="existing-number"><option value="dot">1,234.56 — decimal point</option><option value="comma">1.234,56 — decimal comma</option></select></div><div><label for="existing-date">Text date order</label><select id="existing-date"><option value="dmy">Day / Month / Year</option><option value="mdy">Month / Day / Year</option></select></div></div><button id="existing-open" class="primary">Open Live Analytics →</button>`;
    host.querySelector('#existing-open').onclick=()=>{const roles={};for(const role of ['Amount','Date','Description','Currency']){const value=host.querySelector('#existing-'+role).value;if(value!=='')roles[role]=Number(value);}if(roles.Amount==null)return fail('Choose the Amount column first.');if(new Set(Object.values(roles)).size!==Object.keys(roles).length)return fail('Each column can have only one role.');host.querySelector('#existing-status').textContent='Normalizing records and preparing analytics…';host.querySelector('#existing-busy').hidden=false;client.send({type:'existing-confirm',roles,numberStyle:host.querySelector('#existing-number').value,dateOrder:host.querySelector('#existing-date').value,name:file.name});};
  }
  host.innerHTML=`<p class="eyebrow">Explore existing</p><h1>Welcome back<br>to your report.</h1><div class="panel"><h2>Open your Business Flow report</h2><p>Reopen saved data in Live Analytics without rebuilding it from the original source.</p><div class="drop" id="existing-drop"><h3>Drop a previously generated Business Flow Excel file here</h3><label for="existing-file">Choose Business Flow File</label><input type="file" id="existing-file" accept=".xlsx"></div><p class="help">.xlsx files up to 20 MB · Encrypted workbooks are unsupported. Save an unprotected copy in Excel to open it here.</p><p>✓ Your report is read locally in your browser and is not uploaded to DeTleng.</p><p id="existing-status" role="status" aria-live="polite"></p><progress id="existing-busy" aria-label="Reading Business Flow report" hidden></progress><button id="existing-cancel" hidden>Cancel reading</button><div id="existing-confirm"></div><button id="existing-create">Create New Report →</button></div>`;
  host.querySelector('#existing-file').onchange=e=>load(e.target.files[0]);const drop=host.querySelector('#existing-drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');load(e.dataTransfer.files[0]);};
  host.querySelector('#existing-cancel').onclick=()=>{sequence++;client.cancel();fail('Reading canceled. Choose a file to try again.');};host.querySelector('#existing-create').onclick=()=>{close();create?.();};
  function close(){closed=true;sequence++;client.cancel();detected=null;file=null;if(blobUrl)URL.revokeObjectURL(blobUrl);host.innerHTML='';}
  const heading=host.querySelector('h1');heading.tabIndex=-1;heading.focus();return {close};
}
