import './experience.css';
import {experienceShell,flow,buttons,esc} from './experience-shell.js';
import {HELP,SCENES,JOURNEYS,SHEETS,DEMO} from './guide-content.js';
const state={journey:'all',index:0,output:'blank',amount:'400',period:'all',sheet:'Report Data',samplePeriod:'all',by:'Customer',values:'all',metric:'Net Flow',chart:'Bar'};
export function openGuide(actions,onClose){
 const shell=experienceShell({label:'Business Flow Quick Guide',onClose}),s=state;
 const route=key=>{shell.close();actions[key]();};
 const choices=()=>'<div class="experience-doors">'+[['build','BUILD','I need a workbook'],['create','CREATE','I already have business data'],['explore','EXPLORE','I already have a Business Flow report']].map(([id,title,text])=>'<button data-journey="'+id+'"><b>'+title+'</b><span>'+text+'</span><small>Show me →</small></button>').join('')+'</div>';
 const ready=()=>'<div class="experience-doors">'+[['build','Build Your Workbook'],['create','Create a Business Flow Report'],['explore','Explore an Existing Report']].map(([id,text])=>'<button class="primary" data-route="'+id+'">'+text+' →</button>').join('')+'</div>';
 function scene(id){
 if(id==='welcome')return choices()+'<button class="primary" data-everything>Show Me Everything →</button>';
 if(id==='build')return flow(['Workbook type','Columns','Settings','Blank or Sample'])+buttons([['blank','Blank Workbook'],['sample','Sample Workbook']],'output',s.output)+'<div class="experience-demo"><h3>'+ (s.output==='blank'?'Structure ready. Yours to fill.':'Structure + demonstration data ready.')+'</h3>'+flow(s.output==='blank'?['Download blank workbook','Add real data over time','Return to Create a Report']:['Download sample or Use in Business Flow','Generate report','Open Live Analytics'])+'<p>'+ (s.output==='blank'?'Supported workbook information helps restore your setup when you return.':'Synthetic data lets you try the product immediately.')+'</p></div>';
 if(id==='create')return flow(['Upload Excel','Choose Sheet','Choose Columns','Map Roles','Choose Period','Generate'])+'<div class="experience-demo"><h3>What does Amount mean?</h3>'+buttons([['400','+400'],['-250','−250'],['0','0']],'amount',s.amount)+'<p class="experience-answer" role="status">'+(s.amount==='400'?'+400 → Inflow':s.amount==='-250'?'−250 → Outflow':'0 → Report Data only')+'</p><p>'+HELP.amount+'</p><h3>Choose a reporting period</h3>'+buttons([['all','All Records'],['month','This Month'],['quarter','Quarter'],['year','Year'],['custom','Custom']],'period',s.period)+'<p>'+ (s.period==='custom'?'Custom: choose inclusive start and end dates. ':'')+'The selected period applies consistently to reports and analysis.</p><p class="help">Date, Description, Amount, Currency, Reference and Notes can be mapped where available. Amount is the key field for monetary flow; currencies remain separate.</p></div>';
 if(id==='report')return '<div class="experience-demo"><p class="eyebrow">Example workbook · click a sheet</p>'+buttons(Object.keys(SHEETS).map(x=>[x,x]),'sheet',s.sheet)+'<h3 role="status">'+esc(s.sheet)+'</h3><p>'+SHEETS[s.sheet]+'</p><div class="mini-grid" aria-hidden="true"><span>Date</span><span>Description</span><span>Amount</span><span>2026-07-01</span><span>Example sale</span><span>+400</span><span>2026-07-02</span><span>Example purchase</span><span>−250</span></div></div>';
 if(id==='live'){
 const source=s.values==='all'?DEMO[s.samplePeriod]:DEMO[s.values],factor=s.values==='all'||s.samplePeriod==='all'?1:s.samplePeriod==='q1'?.4:.6,values=source.map((x,i)=>i===3?Math.round(x*factor):Math.round(x*factor)),names=['Inflows','Outflows','Net Flow','Transactions'];
 const base=s.metric==='Average Transaction'?values[2]/values[3]:values[{'Inflows':0,'Outflows':1,'Net Flow':2,'Transaction Count':3}[s.metric]??2];
 const groupDemo='<div class="example-groups" aria-label="Illustrative group comparison">'+['A','B','C'].map((x,i)=>'<div class="example-group"><span>'+esc(s.by)+' '+x+'</span><i style="width:'+ [90,60,30][i]+'%" aria-hidden="true"></i><span>'+Math.round(base*[.5,.3,.2][i]).toLocaleString()+'</span></div>').join('')+'</div>';
 return '<div class="experience-demo"><p class="eyebrow">Sample view · fictional values</p><div class="grid"><label>Period<select data-select="samplePeriod">'+['all','q1','q2'].map(x=>'<option value="'+x+'" '+(s.samplePeriod===x?'selected':'')+'>'+({all:'All',q1:'Q1',q2:'Q2'}[x])+'</option>').join('')+'</select></label><label>Analyze by<select data-select="by">'+['Customer','Product','Category'].map(x=>'<option '+(s.by===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label></div><div class="experience-options">'+[['all','All values'],['one',s.by+' B'],['selected',s.by+' A + B']].map(([x,l])=>'<button data-values="'+x+'" aria-pressed="'+(s.values===x)+'">'+l+'</button>').join('')+'<button data-reset>Reset Filters</button></div><p class="help" role="status">Sample filters: '+esc(s.samplePeriod.toUpperCase())+' · '+esc(s.by)+' · '+esc(s.values)+'. '+(s.values==='all'?'Period example.':'Selected-value example; figures illustrate this period and selection.')+'</p><div class="experience-kpis">'+names.map((n,i)=>'<div><span>'+n+'</span><strong>'+values[i].toLocaleString('en-US')+'</strong></div>').join('')+'</div><div class="mini-charts"><div><h3>Inflows vs Outflows</h3><div class="mini-bars" aria-hidden="true"><i style="height:'+values[0]/125+'px"></i><i style="height:'+Math.abs(values[1])/125+'px"></i></div><p>Inflow '+values[0].toLocaleString()+' · Outflow '+values[1].toLocaleString()+'</p></div><div><h3>Net Flow Trend</h3><svg viewBox="0 0 200 100" role="img" aria-label="Illustrative rising trend; not a time-series calculation"><path d="M5 85 L65 60 L125 70 L195 15" fill="none" stroke="currentColor" stroke-width="4"/></svg><p>Illustrative trend · sample net '+values[2].toLocaleString()+'</p></div><div><h3>Flow Mix</h3><div class="mini-mix" style="--mix:'+Math.round(values[0]/(values[0]+Math.abs(values[1]))*100)+'%" aria-hidden="true"></div><p>Inflows '+Math.round(values[0]/(values[0]+Math.abs(values[1]))*100)+'% of total movement.</p></div></div><details><summary>Analytics Explorer: choose your comparison</summary><p>'+HELP.group+'</p>'+buttons(['Inflows','Outflows','Net Flow','Transaction Count','Average Transaction'].map(x=>[x,x]),'metric',s.metric)+buttons(['Bar','Line'].map(x=>[x,x]),'chart',s.chart)+ (s.chart==='Bar'?groupDemo:'<svg viewBox="0 0 200 60" role="img" aria-label="Illustrative group line; sample comparisons shown below"><path d="M10 10 L100 30 L190 50" fill="none" stroke="currentColor" stroke-width="3"/></svg>'+groupDemo)+'<p role="status">Analyze by '+esc(s.by)+' · '+esc(s.metric)+' · Top 10 · '+esc(s.chart)+' chart.</p><p>Explore top groups, largest transactions and repeated activity in the real dashboard.</p></details></div>';
 }
 if(id==='return')return '<div class="experience-twins"><div><h3>Yesterday</h3>'+flow(['Generate Business Flow Report','Download'])+'</div><div><h3>Today</h3>'+flow(['Explore Existing Report','Open saved report','Report recognized','Live Analytics'])+'</div></div><p>You do not need the original source workbook to reopen a supported processed report.</p><button data-recognize>Try the return journey →</button><p data-recognized role="status"></p>';
 if(id==='privacy')return flow(['Your file','Your browser','Your new report'])+'<div class="experience-twins"><div><h3>A lightweight preview</h3><p>Preview limited to 20 rows for performance.</p><p>Download includes all matching records.</p></div><div><h3>No sign-up needed</h3><p>During the current launch experience, create, download and explore without an account.</p><p>Your business data is not uploaded for processing.</p></div></div>';
 return ready()+'<p>Curious how it began?</p><button data-route="story">Behind Business Flow →</button>';
 }
 function draw(focus=true){
 const expanded=!focus&&shell.body.querySelector('.experience-demo details')?.open;
 const list=JOURNEYS[s.journey],id=list[s.index],copy=SCENES[id];
 shell.body.innerHTML='<div class="experience-toolbar"><span role="status">Scene '+(s.index+1)+' of '+list.length+'</span><button data-restart>Restart Guide</button><button data-all>Show Me Everything</button></div><progress value="'+(s.index+1)+'" max="'+list.length+'" aria-label="Quick Guide progress"></progress><details class="decision"><summary>Which option should I choose? Switch journey</summary>'+choices()+'</details><section class="experience-scene"><h1 tabindex="-1">'+copy[0]+'</h1><p class="experience-lead">'+copy[1]+'</p>'+scene(id)+'</section><div class="experience-controls"><button data-back '+(!s.index?'disabled':'')+'>← Back</button><button class="primary" data-next '+(s.index===list.length-1?'disabled':'')+'>Next →</button></div>';
 shell.body.querySelector('[data-next]').onclick=()=>{s.index++;draw();};shell.body.querySelector('[data-back]').onclick=()=>{s.index--;draw();};
 shell.body.querySelector('[data-restart]').onclick=()=>{s.journey='all';s.index=0;draw();};
 const everything=()=>{s.journey='all';s.index=1;draw();};shell.body.querySelector('[data-all]').onclick=everything;shell.body.querySelector('[data-everything]')?.addEventListener('click',everything);
 shell.body.querySelectorAll('[data-journey]').forEach(b=>b.onclick=()=>{s.journey=b.dataset.journey;s.index=0;draw();});
 shell.body.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));
 for(const key of ['output','amount','period','sheet','values','metric','chart'])shell.body.querySelectorAll('[data-'+key+']').forEach(b=>b.onclick=()=>{s[key]=b.dataset[key];draw(false);shell.body.querySelector('[data-'+key+'="'+CSS.escape(s[key])+'"]')?.focus({preventScroll:true});});
 shell.body.querySelectorAll('[data-select]').forEach(el=>el.onchange=()=>{s[el.dataset.select]=el.value;const key=el.dataset.select;draw(false);shell.body.querySelector('[data-select="'+key+'"]').focus({preventScroll:true});});
 shell.body.querySelector('[data-reset]')?.addEventListener('click',()=>{s.samplePeriod='all';s.values='all';draw(false);shell.body.querySelector('[data-reset]').focus();});
 shell.body.querySelector('[data-recognize]')?.addEventListener('click',()=>{shell.body.querySelector('[data-recognized]').textContent='Sample report recognized ✓ → Live Analytics. Welcome back.';});
 if(expanded&&shell.body.querySelector('.experience-demo details'))shell.body.querySelector('.experience-demo details').open=true;
 if(focus)shell.focus();
 }
 draw();return shell;
}
