import {analyze, grouped, discover, currency, groupValue} from './analysis.js';
import {period} from './engine.js';

// Both adapters provide this immutable record-level contract. The workbook is
// never regenerated by an analytics filter, and calculations remain shared.
export function sessionDataset(model, config, data, name='Business Flow report') {
  const range=period(config.period,config.start,config.end);
  return {records:data.records, columns:model.columns, roles:{...config.roles},
    period:{key:config.period,start:range?.[0]||'',end:range?.[1]||''}, metadata:{name,source:'session'},
    dateOrder:config.dateOrder, numberStyle:config.numberStyle};
}
export function initialFilters(dataset) {
  return {period:'all',start:'',end:'',column:dataset.roles.Category??dataset.roles.Description??dataset.columns.find(c=>c.id!==dataset.roles.Amount)?.id??dataset.columns[0]?.id,
    mode:'all',values:[],dateLevel:'day',time:'auto',currency:'',top:10,metric:'net',chart:'horizontal',sort:'metric',direction:'desc',page:0};
}
export function computeLive(dataset, filters) {
  if(dataset.roles.Amount==null)throw Error('Include and map an Amount column to open monetary Live Analytics.');
  const config={roles:dataset.roles,reports:['Analysis'],groups:[],dateOrder:dataset.dateOrder,timeGrouping:filters.time};
  const range=period(filters.period,filters.start,filters.end);
  const g={column:filters.column,dateLevel:filters.dateLevel,mode:filters.mode,values:filters.values};
  const selected=new Set(filters.values), currencies=[...new Set(dataset.records.map(r=>currency(r,config)))].sort();
  const currentCurrency=currencies.includes(filters.currency)?filters.currency:currencies[0];
  const records=dataset.records.filter(r=>(!range||(r.day&&r.day>=range[0]&&r.day<=range[1]))&&currency(r,config)===currentCurrency&&(g.mode==='all'||selected.has(groupValue(r,g,config).key)));
  const analysis=analyze({columns:dataset.columns},config,{records});
  const section=analysis.sections[0];
  const groups=grouped(records,{...g,mode:'all'},config);
  const rank=(field,ascending=false,condition=()=>true)=>groups.filter(condition).sort((a,b)=>ascending?a[field]-b[field]:b[field]-a[field]).slice(0,filters.top||20);
  const rankings={inflows:rank('totalIn',false,r=>r.totalIn>0),outflows:rank('totalOut',true,r=>r.totalOut<0),positive:rank('net',false,r=>r.net>0),negative:rank('net',true,r=>r.net<0),frequent:rank('count')};
  let cumulative=0;const time=(section?.time||[]).map(r=>({...r,cumulative:cumulative+=r.net}));
  const summary=section?.summary;
  const highlight=(field,asc=false)=>[...time].sort((a,b)=>asc?a[field]-b[field]:b[field]-a[field])[0];
  const sortField=filters.sort==='metric'?filters.metric:filters.sort;
  const sorted=[...groups].sort((a,b)=>{let value=sortField==='label'?String(a.label).localeCompare(String(b.label),undefined,{numeric:true}):(sortField==='totalOut'||sortField==='largestOut'?Math.abs(a[sortField]??0)-Math.abs(b[sortField]??0):(a[sortField]??0)-(b[sortField]??0));return filters.direction==='asc'?value:-value;});
  // Time series must remain chronological even when the Explorer metric changes.
  if(filters.chart==='line'&&filters.column===dataset.roles.Date)sorted.sort((a,b)=>String(a.label).localeCompare(String(b.label)));
  const top=filters.top||20;
  const explorer=sorted.slice(0,top),page=Math.max(0,Math.min(filters.page||0,Math.max(0,Math.ceil(records.length/20)-1)));
  const concentration={inflow:summary?.totalIn?rank('totalIn').slice(0,5).reduce((a,r)=>a+r.totalIn,0)/summary.totalIn:null,outflow:summary?.totalOut?rank('totalOut',true).slice(0,5).reduce((a,r)=>a+r.totalOut,0)/summary.totalOut:null};
  const values=discover(dataset.records,g,config);
  return {summary,time,rankings,groups:groups.slice(0,20),groupCount:groups.length,explorer,currencies,currency:currentCurrency,values,concentration,
    highlights:time.length?{highestIn:highlight('totalIn'),highestOut:highlight('totalOut',true),best:highlight('net'),weakest:highlight('net',true),most:highlight('count'),least:highlight('count',true)}:null,
    transactions:records.slice(page*20,page*20+20),page,pages:Math.ceil(records.length/20),count:records.length,
    topIn:section?.topIn||[],topOut:section?.topOut||[],dateAvailable:dataset.roles.Date!=null,
    timeGrouping:analysis.timeGrouping,quality:{invalidAmounts:records.filter(r=>r.amount==null).length,invalidDates:records.filter(r=>!r.day).length,blankGroups:records.filter(r=>groupValue(r,g,config).key==='blank:').length}};
}
