import './experience.css';
import {experienceShell,flow,buttons,esc} from './experience-shell.js';
import {MILESTONES,COLLABORATORS,STORY_SCENES} from './story-content.js';
const memory={index:0,tier:0,stage:0,person:'Human experience',returned:false};
export function openStory(actions,onClose){
 const shell=experienceShell({label:'Behind Business Flow',onClose}),s=memory;
 function scene(){
 if(s.index===0)return '<p class="eyebrow">The Story Behind Business Flow · Every three months…</p>'+flow(['Download bank Excel','Delete unneeded columns','Separate ins','Separate outs','Prepare for accountant'])+'<div class="story-turn"><p>July–September 2026. The same task returned.</p><h2>“Not this time.”</h2><p>The founder helps manage a family-run online teaching academy. The recurring preparation was part of its accountant-led tax-reporting workflow.</p><blockquote>“I wasn’t trying to build a platform. I just didn’t want to prepare the same spreadsheet manually again.”</blockquote><p>The next thought: “Codex can do this.”<br>Then the real question: what exactly should it do?</p><button class="primary" data-begin>Let’s build it →</button></div>';
 if(s.index===1){
 const clean=s.stage>0,separated=s.stage>1;
 return '<div class="experience-demo"><p class="eyebrow">Fictional example · +400, −250, 0</p><div class="story-columns">'+(clean?['Date','Description','Amount']:['Date','Value Date','Description','Reference','Amount','Balance','Currency','Other…']).map(x=>'<span>'+x+'</span>').join('')+'</div><div class="experience-options"><button data-clean '+(clean?'disabled':'')+'>1. Clean it</button><button data-separate '+(!clean||separated?'disabled':'')+'>2. Separate flows</button><button data-raw>Reset example</button></div><div role="status">'+(separated?'<div class="experience-twins"><div><h3>Inflows</h3><strong>+400</strong></div><div><h3>Outflows</h3><strong>−250</strong></div></div><p>0 remains in Report Data. Useful detail is ready for the accountant.</p>':clean?'<p>Useful columns remain. Next, identify the direction of Amount.</p>':'<p>A bank export is ready. The repetitive preparation remains.</p>')+'</div></div><div class="experience-twins story-comparison"><div><h3>Before</h3>'+flow(['Bank Excel','Manual deletion','Manual separation','Accountant'])+'</div><div><h3>After</h3>'+flow(['Compatible business workbook','Business Flow report','Analysis','Live Analytics','Saved report returns'])+'</div></div>';
 }
 if(s.index===2){const t=MILESTONES[s.tier];return '<div class="story-timeline" aria-label="Product evolution">'+MILESTONES.map((x,i)=>'<button data-tier="'+i+'" aria-pressed="'+(i===s.tier)+'" title="'+esc(x[1])+'"><small>'+ (i?'0'+i:'START')+'</small><b>'+esc(x[0])+'</b></button>').join('')+'</div><div class="experience-demo story-reveal"><p class="eyebrow">'+esc(t[0])+'</p><h2>'+esc(t[1])+'</h2><p>'+esc(t[2])+'</p><p><strong>What changed:</strong> '+esc(t[3])+'</p>'+ (s.tier===2?'<div class="story-columns"><span>Amount</span><span>Importe</span><span>Montant</span></div><p>Different fictional headings. The same meaning. Dynamic columns and role mapping made the product useful beyond one bank.</p>':s.tier===3?'<p>Then the saved report asked: “What about me tomorrow?”</p><button data-return>Bring the sample report back →</button><p role="status">'+(s.returned?'Saved report → recognized → the same Live Analytics ✓':'Today: create and download. Tomorrow: Explore Existing Report.')+'</p>':s.tier===4?'<div class="experience-twins"><div><h3>Blank</h3><p>Born structured. Fill with real activity over time.</p></div><div><h3>Sample</h3><p>Born structured and filled with synthetic demonstration data.</p></div></div>':s.tier===5?'<button data-route="guide">Open Quick Guide →</button>':'')+'<button data-milestones>Choose another milestone ↑</button></div>';}
 if(s.index===3)return buttons(Object.keys(COLLABORATORS).map(x=>[x,x]),'person',s.person)+'<div class="experience-demo"><h3 role="status">'+esc(s.person)+'</h3>'+flow(COLLABORATORS[s.person])+'</div><p class="experience-lead">Experience + Thinking + Building = Business Flow</p><p>AI makes more possible. It does not remove the need to identify the right problem, make decisions, test, iterate and finish.</p><h3>The product grew through iteration.</h3>'+flow(['Conversation','Specification','Implementation','Testing','Observation','New question','Next tier'])+'<p>Not one magic prompt.</p>';
 if(s.index===4)return '<div class="experience-twins"><div><h3>My bank spreadsheet → Your business spreadsheet</h3><p>Business Flow asks what a column means, across different headings and languages.</p></div><div><h3>One shared Live Analytics experience</h3><p>A current report and a supported saved report can tell the same numerical story.</p></div><div><h3>Comfortable previews. Complete downloads.</h3><p>Preview limited to 20 rows for performance. Download includes all matching records.</p></div><div><h3>Local processing, by choice</h3><p>Business data should not be sent somewhere unnecessarily. Your workbook is processed in your browser.</p></div></div><p>After the charts, builders and analytics, the original job still matters: take transactions, separate the flow, make the report clear, and avoid repeating the same manual preparation.</p><p class="help">Business Flow supports reporting and analytics. It does not file taxes or replace an accountant.</p>';
 return '<div class="story-turn"><h2>Solve it well.<br>Then ask what it should become next.</h2>'+flow(['Use','Notice','Question','Build','Test','Improve','Use again'])+'<p>One problem. One decision. One useful question after another.</p><p>We are grateful for every question that led to the next one—and for the first problem that started Business Flow.</p><p class="experience-lead">Build. Create. Analyze. Explore.</p></div><div class="experience-doors"><button data-route="home">Explore Business Flow →</button><button data-route="guide">Open Quick Guide →</button><button data-route="build">Build Your Workbook →</button><button data-route="create">Create a Report →</button></div><button data-replay>Replay the Story</button>';
 }
 function draw(focus=true){
 shell.body.innerHTML='<div class="experience-toolbar"><span role="status">Scene '+(s.index+1)+' of 6 · 2–4 minute story</span><button data-skip>Skip Story</button><button data-timeline>Explore the Timeline</button></div><progress value="'+(s.index+1)+'" max="6" aria-label="Story progress"></progress><section class="experience-scene"><h1 tabindex="-1">'+STORY_SCENES[s.index][0]+'</h1><p class="experience-lead">'+STORY_SCENES[s.index][1]+'</p>'+scene()+'</section><div class="experience-controls"><button data-back '+(!s.index?'disabled':'')+'>← Back</button><button class="primary" data-next '+(s.index===5?'disabled':'')+'>Next →</button></div>';
 const click=(key,fn)=>shell.body.querySelector('[data-'+key+']')?.addEventListener('click',fn);
 click('milestones',()=>{shell.body.querySelector('.story-timeline').scrollIntoView({block:'start'});shell.body.querySelector('[data-tier="'+s.tier+'"]').focus({preventScroll:true});});click('skip',shell.close);click('next',()=>{s.index++;draw();});click('back',()=>{s.index--;draw();});click('begin',()=>{s.index=1;draw();});click('timeline',()=>{s.index=2;draw();});click('replay',()=>{Object.assign(s,{index:0,tier:0,stage:0,returned:false});draw();});
 click('clean',()=>{s.stage=1;draw(false);shell.body.querySelector('[data-separate]').focus();});click('separate',()=>{s.stage=2;draw(false);shell.body.querySelector('[data-raw]').focus();});click('raw',()=>{s.stage=0;draw(false);shell.body.querySelector('[data-clean]').focus();});
 click('return',()=>{s.returned=true;draw(false);shell.body.querySelector('[data-return]').focus();});
 shell.body.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{s.tier=+b.dataset.tier;draw(false);shell.body.querySelector('[data-tier="'+s.tier+'"]').focus({preventScroll:true});if(matchMedia('(max-width:760px)').matches)shell.body.querySelector('.story-reveal').scrollIntoView({block:'start'});});
 shell.body.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{s.person=b.dataset.person;draw(false);shell.body.querySelector('[data-person="'+s.person+'"]').focus({preventScroll:true});});
 shell.body.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{shell.close();actions[b.dataset.route]();});
 if(focus)shell.focus();
 }
 draw();return shell;
}
